-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th10 30, 2023 lúc 02:08 PM
-- Phiên bản máy phục vụ: 10.4.27-MariaDB
-- Phiên bản PHP: 8.1.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `bookstore`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `admin`
--

CREATE TABLE `admin` (
  `id_admin` int(32) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Đang đổ dữ liệu cho bảng `admin`
--

INSERT INTO `admin` (`id_admin`, `username`, `password`) VALUES
(1, 'admin', 'admin');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `catalog`
--

CREATE TABLE `catalog` (
  `id_catalog` int(32) NOT NULL,
  `catalogName` varchar(255) NOT NULL,
  `description` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Đang đổ dữ liệu cho bảng `catalog`
--

INSERT INTO `catalog` (`id_catalog`, `catalogName`, `description`) VALUES
(1, 'Truyện tranh', NULL),
(2, 'Light novel', 'light novel'),
(3, 'Giáo dục', 'Giáo dục');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `hoadon`
--

CREATE TABLE `hoadon` (
  `id_order` int(32) NOT NULL,
  `totalPrice` decimal(15,1) NOT NULL,
  `order_userName` varchar(255) NOT NULL,
  `order_userPhone` varchar(255) NOT NULL,
  `order_userAddress` varchar(255) NOT NULL,
  `order_notes` varchar(255) DEFAULT NULL,
  `ngayLap` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'UTC+7'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Đang đổ dữ liệu cho bảng `hoadon`
--

INSERT INTO `hoadon` (`id_order`, `totalPrice`, `order_userName`, `order_userPhone`, `order_userAddress`, `order_notes`, `ngayLap`) VALUES
(8, '480000.0', 'Anh Hoàng', '0345555642', 'vinh', 'jjjjjj', '2023-10-27 14:36:22');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `product`
--

CREATE TABLE `product` (
  `id_product` int(32) NOT NULL,
  `id_catalog` int(32) NOT NULL,
  `productName` varchar(64) NOT NULL,
  `price` decimal(15,1) NOT NULL,
  `image_link` varchar(2000) NOT NULL,
  `productCode` int(32) NOT NULL,
  `ISBN` varchar(32) NOT NULL,
  `pageNumber` int(32) DEFAULT NULL,
  `author` varchar(32) DEFAULT NULL,
  `content` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Đang đổ dữ liệu cho bảng `product`
--

INSERT INTO `product` (`id_product`, `id_catalog`, `productName`, `price`, `image_link`, `productCode`, `ISBN`, `pageNumber`, `author`, `content`) VALUES
(3, 1, 'ĐỘI QUÂN DORAEMON ĐẶC BIỆT - TẬP 9', '18700.0', 'https://product.hstatic.net/200000343865/product/9_42c50f15b50245358fd08382f745e4d0_large.jpg', 2147483647, '978-604-2-31886-0', 204, 'Fujiko F Fujio', 'Chòm sao băng đâm sầm vào Trái Đất thực ra là một con quái vật đáng sợ! Vũ khí bí mật nền văn minh cổ đại truyền lại cho con cháu mà nhóm\r\nDora đang tìm kiếm liệu có đối phó được với nó không?\r\n'),
(4, 1, 'DORAEMON TRANH TRUYỆN MÀU - KỈ NIỆM VỀ BÀ', '25500.0', 'https://product.hstatic.net/200000343865/product/ki-niem-ve-ba_f346347a1cb94995add7c417526f19ca_large.jpg', 2147483647, '978-604-2-31893-8', 112, 'Fujiko F Fujio', 'Tình cờ thấy lại con gấu bông đồ chơi hồi nhỏ, Nobita bỗng nhớ bà da diết. Nobita đã thuyết phục Doraemon cùng lên cỗ máy thời gian trở về thời điểm 8 năm trước, khi cậu mới 3 tuổi. Hồi ấy, Jaian, Suneo, Shizuka... tất cả đều nhỏ xíu. Khi được thấy bà khỏe mạnh đứng trước mặt mình, Nobita đã vô cùng xúc động... Đây là phiên bản tranh truyện màu được vẽ lại từ tập phim hoạt hình cùng tên của tác giả Fujiko.F.Fujio.'),
(5, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 40', '18700.0', 'https://product.hstatic.net/200000343865/product/40_60c041f35c6f44d4b28081d2a0b4f139_large.jpg', 2147483647, '978-604-2-31805-1', 192, 'Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.'),
(6, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 37', '18700.0', 'https://product.hstatic.net/200000343865/product/37_9e8431a55bbf4034a7eba968fe8d2e1b_large.jpg', 2147483647, '978-604-2-31802-0', 188, 'Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.'),
(7, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 30', '18700.0', 'https://product.hstatic.net/200000343865/product/30_d2821aa74e6f4e9d876e33596158f20c_large.jpg', 2147483647, '978-604-2-31795-5', 196, 'Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.'),
(8, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 4', '18700.0', 'https://product.hstatic.net/200000343865/product/4_70e08fe22f5845109d0f94ea9e1dd093_large.jpg', 2147483647, '978-604-2-31769-6', 192, 'Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.'),
(9, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 43', '18700.0', 'https://product.hstatic.net/200000343865/product/43_394c173196744729a147edd3d577c44b_large.jpg', 2147483647, '978-604-2-31808-2', 192, 'Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.'),
(10, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 42', '18700.0', 'https://product.hstatic.net/200000343865/product/42_a01571babdb54175b0d50acb8c897774_large.jpg', 2147483647, '978-604-2-31807-5 ', 192, 'Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.'),
(11, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 41', '18700.0', 'https://product.hstatic.net/200000343865/product/41_e96c6d4b7d804a67b4ea2d892f546a54_large.jpg', 2147483647, '978-604-2-31806-8 ', 192, ' Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.'),
(12, 1, 'DORAEMON HOẠT HÌNH MÀU - NOBITA VÀ VIỆN BẢO TÀNG BẢO BỐI', '29750.0', 'https://product.hstatic.net/200000343865/product/emon-hoat-hinh-mau---nobita-va-vien-bao-tang-bao-boi---tap-1---tb-2023_357f815779f4436f985af8734dab3ba2_large.jpg', 2147483647, '978-604-2-32127-3', 144, 'Fujiko F Fujio', 'Một kẻ nào đó đã đánh cắp chiếc chuông trên cổ Doraemon!\r\nĐể tìm lại chiếc chuông đó, nhóm Nobita đã tới Viện bảo tàng bảo bối ở tương lai! Liệu các cậu ấy có thể giành lại chiếc chuông cho Doraemon thành công...!?'),
(13, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 31', '18700.0', 'https://product.hstatic.net/200000343865/product/31_dcc4ce2cbefa4140a3045fbcb4f1a5eb_large.jpg', 2147483647, '978-604-2-31796-2', 192, 'Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.\r\n\r\nTÁC GIẢ - HỌA SĨ FUJIKO F FUJIO \r\nTên thật là Fujimoto Hiroshi. Ông sinh ngày 1 tháng 12 năm 1933 tại tỉnh Toyama, Nhật Bản. Năm 1951 ông cho ra đời tác phẩm đầu tay “Thiên thần Tama” (đăng dài kì trên báo học sinh tiểu học hằng ngày).\r\nSau đó, ông công bố các tác phẩm sáng tác cùng Abiko Motoo với bút danh “Fujiko Fujio”.\r\nNăm 1987, ông ngừng hợp tác với Abiko, lấy bút danh là FUJIKO F FUJIO và bắt đầu chuyển sang sáng tác truyện tranh hướng tới đối tượng nhi đồng.\r\nNhững tác phẩm tiêu biểu nhất có thể kể đến là “Doraemon”, “Con ma Q-taro (chung bút danh)”, “Perman-Cậu bé siêu nhân”, “Cuốn từ điển kì bí”, “Siêu nhân Mami”…'),
(14, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 25', '18700.0', 'https://product.hstatic.net/200000343865/product/25_862a397b79f141df8d271b4189f8c340_large.jpg', 2147483647, '978-604-2-31790-0', 192, 'Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.\r\n\r\nTÁC GIẢ - HỌA SĨ FUJIKO F FUJIO \r\nTên thật là Fujimoto Hiroshi. Ông sinh ngày 1 tháng 12 năm 1933 tại tỉnh Toyama, Nhật Bản. Năm 1951 ông cho ra đời tác phẩm đầu tay “Thiên thần Tama” (đăng dài kì trên báo học sinh tiểu học hằng ngày).\r\nSau đó, ông công bố các tác phẩm sáng tác cùng Abiko Motoo với bút danh “Fujiko Fujio”.\r\nNăm 1987, ông ngừng hợp tác với Abiko, lấy bút danh là FUJIKO F FUJIO và bắt đầu chuyển sang sáng tác truyện tranh hướng tới đối tượng nhi đồng.\r\nNhững tác phẩm tiêu biểu nhất có thể kể đến là “Doraemon”, “Con ma Q-taro (chung bút danh)”, “Perman-Cậu bé siêu nhân”, “Cuốn từ điển kì bí”, “Siêu nhân Mami”…'),
(15, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 16', '18700.0', 'https://product.hstatic.net/200000343865/product/16_68fac01a136b4aa4aeeef748f102dbe5_large.jpg', 2147483647, '978-604-2-31781-8', 192, 'Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.\r\n\r\nTÁC GIẢ - HỌA SĨ FUJIKO F FUJIO \r\nTên thật là Fujimoto Hiroshi. Ông sinh ngày 1 tháng 12 năm 1933 tại tỉnh Toyama, Nhật Bản. Năm 1951 ông cho ra đời tác phẩm đầu tay “Thiên thần Tama” (đăng dài kì trên báo học sinh tiểu học hằng ngày).\r\nSau đó, ông công bố các tác phẩm sáng tác cùng Abiko Motoo với bút danh “Fujiko Fujio”.\r\nNăm 1987, ông ngừng hợp tác với Abiko, lấy bút danh là FUJIKO F FUJIO và bắt đầu chuyển sang sáng tác truyện tranh hướng tới đối tượng nhi đồng.\r\nNhững tác phẩm tiêu biểu nhất có thể kể đến là “Doraemon”, “Con ma Q-taro (chung bút danh)”, “Perman-Cậu bé siêu nhân”, “Cuốn từ điển kì bí”, “Siêu nhân Mami”…'),
(16, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 28', '18700.0', 'https://product.hstatic.net/200000343865/product/28_a75e3f6ae2bc4c98b3000051ebc40135_large.jpg', 2147483647, '978-604-2-31793-1', 196, 'Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.\r\n\r\nTÁC GIẢ - HỌA SĨ FUJIKO F FUJIO \r\nTên thật là Fujimoto Hiroshi. Ông sinh ngày 1 tháng 12 năm 1933 tại tỉnh Toyama, Nhật Bản. Năm 1951 ông cho ra đời tác phẩm đầu tay “Thiên thần Tama” (đăng dài kì trên báo học sinh tiểu học hằng ngày).\r\nSau đó, ông công bố các tác phẩm sáng tác cùng Abiko Motoo với bút danh “Fujiko Fujio”.\r\nNăm 1987, ông ngừng hợp tác với Abiko, lấy bút danh là FUJIKO F FUJIO và bắt đầu chuyển sang sáng tác truyện tranh hướng tới đối tượng nhi đồng.\r\nNhững tác phẩm tiêu biểu nhất có thể kể đến là “Doraemon”, “Con ma Q-taro (chung bút danh)”, “Perman-Cậu bé siêu nhân”, “Cuốn từ điển kì bí”, “Siêu nhân Mami”…'),
(17, 1, 'DORAEMON TRUYỆN NGẮN - TẬP 10', '18700.0', 'https://product.hstatic.net/200000343865/product/10_b80c99069c0d4e6a8e307b24ed0e930e_large.jpg', 2147483647, '978-604-2-31775-7', 192, 'Fujiko F Fujio', 'Những câu chuyện về chú mèo máy thông minh Doraemon và nhóm bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa chúng ta bước vào thế giới hồn nhiên, trong sáng đầy ắp tiếng cười với một kho bảo bối kì diệu - những bảo bối biến ước mơ của chúng ta thành sự thật. Nhưng trên tất cả Doraemon là hiện thân của tình bạn cao đẹp, của niềm khát khao vươn tới những tầm cao.\r\n\r\nTÁC GIẢ - HỌA SĨ FUJIKO F FUJIO \r\nTên thật là Fujimoto Hiroshi. Ông sinh ngày 1 tháng 12 năm 1933 tại tỉnh Toyama, Nhật Bản. Năm 1951 ông cho ra đời tác phẩm đầu tay “Thiên thần Tama” (đăng dài kì trên báo học sinh tiểu học hằng ngày).\r\nSau đó, ông công bố các tác phẩm sáng tác cùng Abiko Motoo với bút danh “Fujiko Fujio”.\r\nNăm 1987, ông ngừng hợp tác với Abiko, lấy bút danh là FUJIKO F FUJIO và bắt đầu chuyển sang sáng tác truyện tranh hướng tới đối tượng nhi đồng.\r\nNhững tác phẩm tiêu biểu nhất có thể kể đến là “Doraemon”, “Con ma Q-taro (chung bút danh)”, “Perman-Cậu bé siêu nhân”, “Cuốn từ điển kì bí”, “Siêu nhân Mami”…'),
(18, 1, 'DORAEMON TUYỂN TẬP THEO CHỦ ĐỀ - TẬP 9 - NHỮNG CHUYẾN PHIÊU LƯU', '29750.0', 'https://product.hstatic.net/200000343865/product/9_2db1aa1b68f642ed911c9486ca203667_large.jpg', 2147483647, '978-604-2-31938-6', 284, 'Fujiko F Fujio', 'Nobita đã cùng Doraemon phiêu lưu, chu du khắp mọi nơi như bay trên bầu trời cao, khám phá thế giới dưới lòng đất, thậm chí đi ngược dòng thời gian về quá khứ. Chúng ta hãy cùng nhìn lại khuôn mặt rạng rỡ của Nobita vào những lúc như thế nhé! Cậu thực sự thích thú mỗi khi được đi phiêu lưu và khám phá những điều mới lạ. Khi ấy, đôi mắt cậu luôn bừng sáng, khác hẳn so với khuôn mặt phải ngồi vào bàn học bài. Nào, hãy cùng anh bạn Nobita bước vào những chuyến phiêu lưu li kì nhé!'),
(19, 1, 'DORAEMON TUYỂN TẬP THEO CHỦ ĐỀ - TẬP 6 - NHỮNG CÂU CHUYỆN ĐÁNG S', '29750.0', 'https://product.hstatic.net/200000343865/product/6_3bf692804ae24b2bb2373d463ab7f127_large.jpg', 2147483647, '978-604-2-31935-5 ', 284, 'Fujiko F Fujio', 'Trong cuộc đời, không phải cứ quái vật hay ma mới là thứ đáng sợ, ghê rợn. Phải chăng trong cuốn này, Doraemon và Nobita đã cho chúng ta biết rằng chính lòng tham ẩn sâu trong con người chúng ta mới là thứ đáng sợ nhất! Các bạn hãy vừa nghĩ \"Tính cách con người thật kì lạ!\" vừa học 26 mẩu truyện đã được chọn trong cuốn sách này nhé!'),
(20, 1, 'DORAEMON TUYỂN TẬP THEO CHỦ ĐỀ - TẬP 5 - NHỮNG CÂU CHUYỆN CẢM ĐỘ', '29750.0', 'https://product.hstatic.net/200000343865/product/5_be0e978e05864821a958bfb19aee7c37_large.jpg', 2147483647, '978-604-2-31934-8', 284, 'Fujiko F Fujio', 'Trong bộ truyện Doraemon, ta thấy có không ít những mẩu truyện khiến cho ta cảm động và nhận ra rằng thiên nhiên, sinh mệnh một con người hay bạn bè đều là những điều ta đáng phải trân trọng. Chính những thông điệp đầy ý nghĩa từ chú mèo máy Doraemon hiền lành, tốt bụng và các bạn đã chạm tới trái tim của các bạn độc giả một cách nhẹ nhàng, mềm mỏng và xác thực. Mời các bạn đón đọc 20 mẩu truyện với nội dung như vậy đã được chọn ra từ 45 tập truyện ngắn Doraemon trong tập truyện này!'),
(21, 1, 'DORAEMON TRUYỆN DÀI - TẬP 12 - NOBITA VÀ VƯƠNG QUỐC TRÊN MÂY', '18700.0', 'https://product.hstatic.net/200000343865/product/12_903e4bd3ee9041629fcc7bdbdf44aaa3_large.jpg', 2147483647, '978-604-2-31822-8', 192, 'Fujiko F Fujio', 'Fujiko F Fujio\r\nCác em có cho rằng thiên đường tồn tại hay không? Câu chuyện lần này kể về một thế giới trên mây có người trời sinh sống. Nơi ấy là một vương quốc trong mơ có nền văn minh tiến bộ, thiên nhiên tươi đẹp, nhưng không chỉ đơn giản như thế…\r\nChúng ta hãy cùng dõi theo chuyến phiêu lưu kì lạ của nhóm bạn Nobita nhé!'),
(22, 1, 'DORAEMON TRUYỆN DÀI - TẬP 1 - CHÚ KHỦNG LONG CỦA NOBITA', '18700.0', 'https://product.hstatic.net/200000343865/product/1_b7e049659e234c1bb108c966a9a90621_large.jpg', 2147483647, '978-604-2-31811-2', 192, 'Fujiko F Fujio', '“Chú khủng long của Nobita” là tác phẩm mở đầu cho xêri Doraemon truyện dài, và đã được chuyển thể thành phim hoạt hình.\r\nTrong tác phẩm này, 5 người nhóm bạn Doraemon đã ngược dòng thời gian, trở về thế giới khủng long Kỉ Bạch Á. Tất cả đã sát cánh bên nhau trải qua bao nhiêu sóng gió hiểm nguy để bảo vệ chú khủng long mới nở Pisuke.\r\nCác em hãy cùng dõi theo câu chuyện phiêu lưu đầy tình thương yêu và tình bạn này nhé!'),
(23, 1, 'DORAEMON TRUYỆN DÀI - TẬP 24 - NOBITA Ở VƯƠNG QUỐC CHÓ MÈO', '18700.0', 'https://product.hstatic.net/200000343865/product/24_896c179942354940b2f5bb47cb50da70_large.jpg', 2147483647, '978-604-2-31834-1', 192, 'Fujiko F Fujio', '\"Nobita ở vương quốc chó mèo\" là tập thứ 24 trong series truyện dài Doraemon được vẽ và sáng tác bởi Fujiko.F.Fujio. Đây cũng là một trong những tập cảm động nhất trong tất cả 24 tập của series truyện dài.\r\n\r\nTruyện kể về tình bạn gắn bó giữa cậu bé Nobita loài người và chú chó Ichi, sau 1000 năm xa cách cả hai vẫn không quên người kia.\r\n\r\nỞ thế giới của mình, Nobita đã nhặt được một chú chó con đáng yêu và đặt tên là Ichi, không bao lâu sau Nobita và các bạn của mình phát hiện rất nhiều chó mèo bị bỏ rơi; thế nhưng mẹ của Nobita không cho phép cậu bé nuôi thú trong nhà. Nobita đã dùng cỗ máy thời gian của Doraemon để đưa tất cả về quá khứ - trước cả thời kỳ khủng long xuất hiện để bọn chó mèo có thể sống vui vẻ.\r\n\r\nLúc Nobita, Doraemon và các bạn của mình quay lại thăm Ichi và những con vật khác thì bị cuốn vào một cơn lốc xoáy thời gian khiến thời gian thay đổi - cả bọn bước vào thế giới chó mèo 1000 năm sau - lúc này nơi đây đã trở thành một thành phố phồn hoa và thịnh vượng. Trải qua nhiều khó khăn và biến cố cùng với nhau, qua những hiểu lầm ban đầu, Nobita cùng Ichi cuối cùng đã nhận ra nhau.'),
(24, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 100 (TẶNG KÈM POSTCARD VUÔNG CONAN', '17000.0', 'https://product.hstatic.net/200000343865/product/100_bd275c22338e4df3a7b01a0b8553e338_large.jpg', 2147483647, '978-604-2-27297-1', 184, 'Gosho Aoyama', 'Những thi thể không rõ danh tính liên tục được phát hiện… Thủ phạm là tổ chức Áo đen.\r\nĐối thủ là Gin, Vodka, Chianti, Korn, Vermouth, Kir, và RUM. Kết thúc cuộc đấu trí cân tài cân sức ấy, sự thật được đưa ra ánh sáng là…\r\n\r\nGOSHO AOYAMA\r\nChào các bạn, tôi là Aoyama! Hồi vẽ series “FBI vs Tổ chức Áo đen” trong tập này, tôi đã đội mưa tới “Công viên Umikaze” – hình mẫu của “Công viên Namikaze” – để lấy tư liệu đó!\r\nTựa người vào lan can, cầm ô như súng trường, hướng mũi ô về phía “đảo Saru” – hình mẫu của “đảo Umizaru” – tôi phấn khích hét lên với biên tập viên: “Ngắm bắn từ đây mà trúng được! Akai siêu thật!!” rồi hứng trọn những ánh mắt hình viên đạn của các cần thủ xung quanh…\r\nĐã mất công như vậy nên tôi đưa chi tiết cần thủ vào truyện luôn (Ha ha).'),
(25, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 25', '25000.0', 'https://product.hstatic.net/200000343865/product/25_d1dc4c1b9263426cbb4ed3a2da643f3d_large.jpg', 2147483647, '978-604-2-31640-8', 196, 'Gosho Aoyama', 'Vừa mới vào trong hang động để thám hiểm, chúng tớ xui xẻo gặp ngay bọn tội phạm giết người cướp của!! Đen đủi hơn, do bất cẩn tớ còn bị một phát đạn vào bụng nên không thể đi tiếp được!! Bây giờ chỉ còn biết trông cậy vào 3 thành viên của đội thám tử nhí mà thôi... Không biết liệu chúng tớ có vượt qua được nguy hiểm này không!?'),
(26, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 50', '25000.0', 'https://product.hstatic.net/200000343865/product/50_ba55a5ee4f924cc382aac2b639d5e074_large.jpg', 2147483647, '978-604-2-31665-1', 188, 'Gosho Aoyama', 'Ở nhà hàng nơi Conan và các bạn đang ăn uống có một cuộc hẹn hò tập thể. Những người tham dự thật bất ngờ lại là nhóm Sato, Takagi, Chiba, Yumi. Nhưng trong lúc tất cả đang vui vẻ,  em họ của một người bị bắt cóc! Theo như điều tra của Sato và nhóm Conan, có 3 người tình nghi đều là người quen! Khi mà Conan đang suy luận tìm ra hung thủ thì trung sĩ Takagi đã hành động… Ngoài ra, trong tập này cũng có câu chuyện phá án thời Kudo Shinichi và Hattori Heiji còn học cấp 2!!'),
(27, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 86', '25000.0', 'https://product.hstatic.net/200000343865/product/86_d126ae46cf754462a25cf3ef71295471_large.jpg', 2147483647, '978-604-2-31701-6', 184, 'Gosho Aoyama', 'Thi thể đã biến đi đâu!? “Vụ án xác chết biến mất trong bể bơi” sẽ được làm sáng tỏ! Bên cạnh đó, bóng dáng “Rum”, nhân vật quyền lực thứ 2 của tổm chức Áo Đen sẽ theo sát Conan và haibara!? Cũng trong tập này, “vụ án người cô thân thiết”, vụ án mạng quái vật “kamaitachi” với sự tham gia của heiji... và mở đầu của “án mạng kawanakajima” nơi máu của các cảnh sát hình sự sẽ đổ xuống chiến trường xưa ở tỉnh Nagano... hứa hẹn sẽ mang tới nhiều điều bất ngờ!'),
(28, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 11', '25000.0', 'https://product.hstatic.net/200000343865/product/11_85a34f57d4ca41a79491d5cb6da4c54b_large.jpg', 2147483647, '978-604-2-31626-2', 180, 'Gosho Aoyama', 'Tớ là Kudo Shinichi, một thám tử thiếu niên có đôi chút tiếng tăm. Đáng ra là như vậy... Nhưng nếu bạn để ý thì Kudo tớ đây đã trở thành cậu bé cấp 1 từ lúc nào mất rồi. Dù bề ngoài là trẻ con nhưng tớ vẫn sở hữu cái đầu của người lớn, đủ để phá được những vụ án rắc rối, không thua gì lúc bình thường đâu! Nói gì thì sự thật lúc nào cũng chỉ có một, phải không các bạn!?'),
(29, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 14', '25000.0', 'https://product.hstatic.net/200000343865/product/14_e53c1e02091c4708b9b2d8b75ff50910_large.jpg', 2147483647, '978-604-2-31629-3', 184, 'Gosho Aoyama', 'Che giấu thân phận và tham gia vào đội thám tử nhí... Mọi vụ án đều được giải quyết rất nhanh chóng... Nhưng hình như Ran bắt đầu nghi ngờ về thân phận tớ rồi!? Biết làm sao đây... Tớ không thể nói với bất kì ai rằng Conan chính là Kudo Shinichi được!!!'),
(30, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 97', '25000.0', 'https://product.hstatic.net/200000343865/product/97_c26db968b3ab4a928f12fbdab83362c1_large.jpg', 2147483647, '978-604-2-31712-2', 184, 'Gosho Aoyama', 'Kogoro, Amuro Toru, và Wakita Kanenori. Bộ tứ kì lạ ấy cùng nhau đi tới một nhà thờ bỏ hoang ẩn mình trong núi sâu ở Nagano.\r\n\r\nPhải chăng chờ đợi họ ở đó là án mạng và những mật mã bí ẩn!? Giữa lúc ấy, Conan cố gắng tìm kiếm gợi ý quan trọng liên quan tới chân tướng của “RUM” từ Amuro…!'),
(31, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 88', '25000.0', 'https://product.hstatic.net/200000343865/product/88_6fc7dd1c73c044a1908c1880fd726a5e_large.jpg', 2147483647, '978-604-2-31703-0', 184, 'Gosho Aoyama', 'Cuối cùng “Scotch”, thành viên mới của tổ chức ao Đen cũng xuất hiện! amuro và akai từng quen biết trong quá khứ, rốt cuộc mối quan hệ giữa họ là gì!?'),
(32, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 44', '25000.0', 'https://product.hstatic.net/200000343865/product/44_9360e5ec599944deacccb945cd8cec62_large.jpg', 2147483647, '978-604-2-31659-0', 192, 'Gosho Aoyama', 'Ông bác của Sonoko, Suzuki Jirokichi đã đăng tin trên báo để thách thức siêu đạo chích Kid đến ăn trộm Big Jewel, \"Kì tích của biển cả\". Siêu trộm Kid chấp nhận lời thách thức và xuất hiện một cách ngoạn mục bất chấp sự bảo vệ nghiêm ngặt. Conan và Kid, thật là một cuộc đối đầu của trí tuệ. Ai sẽ là người chiến thắng đây!?'),
(33, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 28', '25000.0', 'https://product.hstatic.net/200000343865/product/28_18d416611a3040bdb7b407ff0dbb3051_large.jpg', 2147483647, '978-604-2-31643-9', 192, 'Gosho Aoyama', 'Vì bức thư gửi tới chỗ Heiji mà bọn Conan tới hòn đảo được cho là có người cá... Ở đây có 1 người già trường sinh bất lão, giờ đã thọ 130 tuổi nhờ ăn thịt người cá?! Từ đêm đó, các vụ án giết người liên tiếp bắt đầu!?'),
(34, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 95', '25000.0', 'https://product.hstatic.net/200000343865/product/95_21cfa365b4d1466890e20869fab64fdb_large.jpg', 2147483647, '978-604-2-31710-8', 184, 'Gosho Aoyama', 'Tạm thời trở lại là “Shinichi”, Conan cùng Ran và các bạn tham gia chuyến du lịch ngoại khóa tới Kyoto!\r\n... Nhưng một loạt án mạng đã liên tiếp xảy ra!?\r\nVà bí ẩn lớn nhất của “Thám tử lừng danh Conan”, danh tính Boss của “Tổ chức Áo Đen” sắp được tiết lộ!?'),
(35, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 65', '25000.0', 'https://product.hstatic.net/200000343865/product/65_55c1625c31c4402bb58f413f02fae13c_large.jpg', 2147483647, '978-604-2-31680-4', 180, 'Gosho Aoyama', 'Đáp lại lời thỉnh cầu của thanh tra Yamato Kansuke, Conan và mọi người bắt tay vào giải đố về vụ giết người với bức tường đỏ nhuốm máu. Cả kì phùng địch thủ của Kansuke là thanh tra Morofushi Komei cũng cộng tác để dần làm sáng tỏ âm mưu trên bức tường. Mời các bạn thưởng thức cả “Gặp lại siêu đạo chích Kid và chiếc két Tanuki”, “2 người đồng hành nguy hiểm” và “Nhóm thám tử vs bọn cướp ngân hàng”…'),
(36, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 23', '25000.0', 'https://product.hstatic.net/200000343865/product/23_97eeb36cf22140d3a8634a14529af953_large.jpg', 2147483647, '978-604-2-31638-5', 180, 'Gosho Aoyama', 'Cảnh sát thì cũng vẫn chỉ là con người mà thôi. Có thích người này người kia cũng là điều dễ hiểu! Cô nàng mình thích lại đi thích người khác à? Tưởng gì, chuyện này nhiều như cơm bữa... Chàng cảnh sát Takagi đã phải lòng nữ cảnh sát xinh đẹp phòng điều tra số 1 mất rồi!!'),
(37, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 22', '25000.0', 'https://product.hstatic.net/200000343865/product/22_694d4f9bdcb049cd8917727f7c3aa782_large.jpg', 2147483647, '978-604-2-31637-8', 180, 'Gosho Aoyama', 'Trên chuyến tàu tốc hành có giường nằm đến Hokkaido mang tên \"Hokutosei\", chúng tớ lại gặp phải một vụ án mạng... Liệu có phải hung thủ đã đập vỡ cửa sổ trong lúc tày chạy trong đường hầm và tẩu thoát!? Một điều lạ là, những tình tiết của vụ án này có gì đó rất giống với nội dung cuốn tiểu thuyết mà bố tớ đã viết.'),
(38, 1, 'THÁM TỬ LỪNG DANH CONAN - TẬP 12', '25000.0', 'https://product.hstatic.net/200000343865/product/12_a197513519e543a195954f6178fba949_large.jpg', 2147483647, '978-604-2-31627-9 ', 180, 'Gosho Aoyama', 'Tớ là Edogawa Conan. Nhưng có một điều các bạn nên biết, thực chất tớ là Kudo Shinichi, thám tử học sinh cấp 3. Phải mất công lắm mới tìm thấy bọn người áo đen đã biến mình trở thành cậu bé cấp 1, vậy mà... Không hiểu sao, lần này tớ linh cảm có chuyện không hay sắp xảy ra...'),
(39, 1, 'SIÊU LẬP DỊ CHIẾN ÁC MA ANDY', '45500.0', 'https://product.hstatic.net/200000343865/product/sieu-lap-di-chien-ac-ma-andy_d8b16b57b63342dda9edd75933b99734_large.jpg', 2147483647, '978-604-2-33128-9', 64, 'Jess Bradley', '“Một xê ri mới lạ đầy hấp dẫn dành cho các fan hâm mộ của Nhật Kí Chú Bé Nhút Nhát và Siêu Nhân Quần Chíp.” Theo TẠP CHÍ THƯ VIỆN TRƯỜNG HỌC\r\nAndy nắm giữ một bí mật phi thường. Cây bút chì của cậu có thể vẽ mọi thứ biến thành thật! Thế nhưng, thời điểm cậu tạo ra một BẢN SAO để làm việc vặt cho mình thì mọi thứ dần trở nên tồi tệ. Liệu Andy có thể sống sót trong trận chiến với PHIÊN BẢN ÁC MA của chính mình không?\r\n---\r\nAndy là một cậu học trò nhút nhát nhưng mê vẽ vời. Trong chuyến dã ngoại với lớp đến Đảo Sinh Tồn, tình cờ cây bút chì của cậu bị nhiễm phóng xạ và có siêu năng lực “vẽ thứ gì là thứ đó biến thành thật”. Cùng với cô bạn Mona thông minh tuyệt vời và cậu em trai Oscar nghịch ngợm, Andy sẽ tiêu diệt những tên siêu tội phạm và bảo vệ thế giới ra sao? Mời bạn tìm đọc trọn bộ Siêu Lập Dị để tham gia vào những cuộc phiêu lưu vô cùng hấp dẫn và hài hước của cậu bé Andy nhé!\r\nMời các bạn đón đọc trọn bộ Siêu Lập Dị (4 cuốn):\r\n•    Siêu Lập Dị Và Cây Bút Chì Định Mệnh - Đánh Bại Quái Vật Trước Bữa Tối\r\n•    Siêu Lập Dị Đối Đầu Tiến Sĩ Mông Gôm\r\n•    Siêu Lập Dị Chiến Ác Ma Andy\r\n•    Siêu Lập Dị Và Chiếc Kèn Thời Gian'),
(40, 1, 'SIÊU LẬP DỊ VÀ CÂY BÚT CHÌ ĐỊNH MỆNH - ĐÁNH BẠI QUÁI VẬT TRƯỚC B', '45500.0', 'https://product.hstatic.net/200000343865/product/sieu-lap-di-va-cay-but-chi-dinh-menh_fc4ad70bf9d14f21a197ca9eba541799_large.jpg', 2147483647, '978-604-2-33127-2', 64, 'Jess Bradley', 'Andy có thể hơi nhút nhát, nhưng cậu là một DÂN VẼ ĐẦY ÓC SÁNG TẠO đẳng cấp thế giới. Thời điểm cây bút chì của Andy bị CHẤT THẢI PHÓNG XẠ biến đổi, cậu chợt phát hiện ra mình có khả năng vẽ mọi thứ biến thành thật – đó là lúc một SIÊU ANH HÙNG mới ra đời!\r\n---\r\nAndy là một cậu học trò nhút nhát nhưng mê vẽ vời. Trong chuyến dã ngoại với lớp đến Đảo Sinh Tồn, tình cờ cây bút chì của cậu bị nhiễm phóng xạ và có siêu năng lực “vẽ thứ gì là thứ đó biến thành thật”. Cùng với cô bạn Mona thông minh tuyệt vời và cậu em trai Oscar nghịch ngợm, Andy sẽ tiêu diệt những tên siêu tội phạm và bảo vệ thế giới ra sao? Mời bạn tìm đọc trọn bộ Siêu Lập Dị để tham gia vào những cuộc phiêu lưu vô cùng hấp dẫn và hài hước của cậu bé Andy nhé!\r\nMời các bạn đón đọc trọn bộ Siêu Lập Dị (4 cuốn):\r\n•    Siêu Lập Dị Và Cây Bút Chì Định Mệnh - Đánh Bại Quái Vật Trước Bữa Tối\r\n•    Siêu Lập Dị Đối Đầu Tiến Sĩ Mông Gôm\r\n•    Siêu Lập Dị Chiến Ác Ma Andy\r\n•    Siêu Lập Dị Và Chiếc Kèn Thời Gian'),
(41, 1, 'CỔ TÍCH VIỆT NAM CHO BÉ MẪU GIÁO - SỰ TÍCH BÁNH CHƯNG BÁNH DÀY', '20000.0', 'https://product.hstatic.net/200000343865/product/su-tich-banh-chung-banh-day_3d4ec1033ec04670a6280ec652b42edc_large.jpg', 2147483647, '978-604-2-29143-9', 20, 'Hiếu Minh', 'Các em có biết món bánh chưng và bánh dày quen thuộc của người Việt mình đến từ đâu không? Câu chuyện này sẽ góp một cách giải thích về nguồn gốc của hai món bánh truyền thống ấy đấy!\r\nBộ “Cổ tích Việt Nam cho bé” tuyển chọn những câu chuyện nổi tiếng của kho tàng chuyện cổ tích Việt Nam, được kể lại ngắn gọn, súc tích cùng với hình minh họa đẹp phù hợp với lứa tuổi mẫu giáo, tiểu học.'),
(42, 1, 'CỔ TÍCH VIỆT NAM CHO BÉ MẪU GIÁO - SƠN TINH - THUỶ TINH', '20000.0', 'https://product.hstatic.net/200000343865/product/son-tinh-thuy-tinh_9af1ffdc6359417aae73f5360e975cc7_large.jpg', 2147483647, '978-604-2-29140-8', 20, 'Hiếu Minh', 'Sơn Tinh - Thủy Tinh luôn là một truyền thuyết bất tử trong kho tàng dân gian Việt Nam. Hai vị thần đã cầu hôn nàng công chúa xinh đẹp như thế nào? Chúng mình cùng đọc truyện nhé!\r\n\r\nBộ “Cổ tích Việt Nam cho bé mẫu giáo” bao gồm những câu chuyện nổi tiếng của kho tàng chuyện cổ tích Việt Nam, được kể lại ngắn gọn, súc tích cùng với hình minh họa đẹp phù hợp với lứa tuổi mẫu giáo.'),
(43, 1, 'CỔ TÍCH VIỆT NAM CHO BÉ MẪU GIÁO - CÂY TRE TRĂM ĐỐT', '20000.0', 'https://product.hstatic.net/200000343865/product/cay-tre-tram-dot_26201a7d443d420b99e7ac241d3fdcc8_large.jpg', 2147483647, '978-604-2-29123-1', 20, 'Kim Ngọc', 'Có lão phú ông bủn xỉn, hành hạ kẻ ở đủ đường. Lão hứa gả con gái, để bắt anh đầy tớ dốc sức làm lụng ngày đêm. Nhưng ít lâu sau, vì muốn gả con gái cho một nhà giàu, lão chủ lại nghĩ mưu tính kế, bắt anh đầy tớ đi tìm cho được cây tre có một trăm đốt thì mới được lấy cô gái kia làm vợ. Nhưng liệu có cây tre nào cao đủ một trăm đốt? Anh đầy tớ phải làm sao?\r\n\r\nMời các em cùng đọc truyện!'),
(44, 1, 'TÝ QUẬY - TẬP 13', '40000.0', 'https://product.hstatic.net/200000343865/product/13_96a50f23f2514a25a41381cc637cfae3_large.jpg', 2147483647, '978-604-2-33014-5', 160, 'Đào Hải', 'Tý Quậy tập 13 tiếp tục giới thiệu 4 mẩu chuyện mới toanh về Tý, Tèo, Tún – bộ ba gây cười “trứ danh” của xê-ri Tý Quậy. Ở tập truyện mới này, Tý phải đương đầu với những tình huống vô cùng “ngặt nghèo” như bị bố mẹ so sánh với “con nhà người ta”, với bài tập tiếng Việt tưởng dễ mà lại khó không tưởng, với ngày lễ Giáng Sinh và kì nghỉ hè “trong mơ”. Vẫn hài hước và đáng yêu đậm chất Tý Quậy, tập truyện tranh này hứa hẹn mang tới cho các độc giả trung thành của Tý những tràng cười sảng khoái! '),
(45, 1, 'VUN ĐẮP TÂM HỒN - NẾU TỚ CÓ MỘT BẠN CHUỘT TÚI', '40000.0', 'https://product.hstatic.net/200000343865/product/vun-dap-tam-hon_neu-to-co-mot-ban-chuot-tui_0904650409704fc3a9f06672e68a78e8_large.jpg', 2147483647, '978-604-2-32964-4', 32, 'Alex Barrow', '“Tớ muốn một bạn thú QUẬY TƯNG\r\nThích vui chơi tưng bừng cả ngày...\r\nNăng động nên sẽ mê tơi\r\nMột cuốc chạy bộ chào ngày mới.\r\nTưởng tượng xem, nếu tớ có một... bạn chuột túi!”\r\n---\r\nBộ sách Vun Đắp Tâm Hồn - Nếu Tớ Có… được đọc trên chương trình Chuyện kể ngủ ngon của kênh Cbeebies.\r\nBằng những câu từ đậm chất thơ và tranh vẽ tuyệt đẹp, quyển sách sẽ đưa bé vào một thế giới tưởng tượng đầy màu sắc và vô cùng kì thú.'),
(46, 1, 'ASTÉRIX - VÙNG ĐẤT THẦN THÁNH', '56000.0', 'https://product.hstatic.net/200000343865/product/asterix_vung-dat-thanh_tb-2023_f14f5f3abc4c48d4bcd28bb8971606db_large.jpg', 2147483647, '978-604-2-32998-9 ', 52, 'René Goscinny', 'ASTÉRIX ĐÃ TRỞ LẠI!\r\nCésar đưa ra một quyết định trọng đại: Ông muốn phá hủy khu rừng bao quanh làng Gaulois để xây dựng Vùng đất thần thánh và buộc họ phải đầu hàng đế quốc La Mã. Dân làng Gaulois, cùng người hùng Astérix của chúng ta sẽ ngăn chăn âm mưu thâm độc này thế nào? Hãy cùng đón đọc trong ASTÉRIX – VÙNG ĐẤT THẦN THÁNH!\r\n-------\r\nXuất hiện lần đầu tiên trên tạp chí truyện tranh dành cho thiếu nhi Pilote vào ngày 29 tháng 10 năm 1959, bộ truyện tranh Astérix đã được chuyển ngữ sang 107 thứ tiếng, xuất bản gần 400 triệu bản trên toàn thế giới.\r\nẤn bản của NXB Kim Đồng được dịch từ nguyên bản tiếng Pháp, in màu toàn bộ trên giấy định lượng cao.'),
(47, 1, 'ASTÉRIX - ASTÉRIX VÀ NỮ HOÀNG CLÉOPÂTRE', '56000.0', 'https://product.hstatic.net/200000343865/product/asterix_asterix-va-nu-hoang-cleopatre_tb-2023_3fbfb1dd5fad4062bf560c634cbd6d2b_large.jpg', 2147483647, '978-604-2-32996-5 ', 56, 'René Goscinny', 'ASTÉRIX ĐÃ TRỞ LẠI!\r\nNhận lời nhờ vả từ người bạn cũ của pháp sư Panoramix, Astérix và Obelix lên đường tới Ai Cập để giúp nữ hoàng Cléopâtre xây dựng cung điện cho César. Tiếc rằng, không phải ai cũng ủng hộ chuyến hành trình này.\r\nLiệu những người anh hùng của chúng ta có một lần nữa khải hoàn về làng Gaulois? Hãy cùng xem tiếp trong ASTÉRIX VÀ NỮ HOÀNG CLÉOPÂTRE nhé!\r\n-------\r\nXuất hiện lần đầu tiên trên tạp chí truyện tranh dành cho thiếu nhi Pilote vào ngày 29 tháng 10 năm 1959, bộ truyện tranh Astérix đã được chuyển ngữ sang 107 thứ tiếng, xuất bản gần 400 triệu bản trên toàn thế giới.\r\nẤn bản của NXB Kim Đồng được dịch từ nguyên bản tiếng Pháp, in màu toàn bộ trên giấy định lượng cao.'),
(48, 1, 'ÔNG NGOẠI CHIM CÁNH CỤT', '40000.0', 'https://product.hstatic.net/200000343865/product/morag-hood_ong-ngoai-chim-canh-cut_76aedd74a70d4b8589a0e5ce25ae7340_large.jpg', 2147483647, '978-604-2-32852-4', 32, 'Morag Hood', 'Dạo này ông ngoại lạ lùng quá! Quần áo ông mặc rộng ơi là rộng. Hành động và lời nói của ông cũng chẳng giống thường ngày...\r\nCó phải ông đang giấu bí mật gì chăng?\r\n---\r\nMorag Hood là tác giả và họa sĩ minh họa sách thiếu nhi đến từ Edinburgh (Scotland). Cô có bằng Thạc sĩ về Minh họa sách thiếu nhi của Trường Nghệ thuật Cambridge, và từng đoạt nhiều giải thưởng uy tín về minh họa sách.\r\nCác tác phẩm của cô có phong cách kể chuyện độc đáo, phần lời và tranh hòa quyện vào nhau, đầy hài hước và bất ngờ. Qua 7 cuốn sách tranh rực rỡ sắc màu, các bạn nhỏ sẽ được phiêu lưu vào thế giới sáng tạo rất thú vị của Morag Hood!'),
(49, 1, 'BẠN CÁ SẤU THÂN THIỆN - NHỮNG MẨU TRUYỆN NHO NHỎ', '49000.0', 'https://product.hstatic.net/200000343865/product/ban-ca-sau-than-thien_nhung-mau-truyen-nho-nho_ee8ab2790d084f35880b06559ac913c7_large.jpg', 2147483647, '978-604-2-33106-7', 140, 'Chow Hon Lam', 'Khác với tưởng tượng thường thấy về loài cá sấu, Buddy Gator lại là một chú cá sấu ấm áp và ngọt ngào. Cậu luôn sống tử tế, yêu thương mọi người xung quanh. Bởi thế, có lẽ tất cả chúng ta đều cần một người bạn như cậu ấy.\r\nNhững mẩu truyện tranh ngắn duyên dáng và hóm hỉnh của Chow Hon Lam đã ghi lại những khoảnh khắc của lòng tốt, của tình bạn, tình yêu, của sự tôn trọng và chia sẻ. Bộ sách nhỏ về chàng cá sấu thân thiện sẽ đem đến cho người đọc những cảm xúc tích cực – món quà hoàn hảo cho cả trẻ em và người lớn. '),
(50, 1, 'BẠN CÁ SẤU THÂN THIỆN - TÌNH BẠN DIỆU KÌ', '49000.0', 'https://product.hstatic.net/200000343865/product/ban-ca-sau-than-thien_tinh-ban-dieu-ki_7992e55d0400430d98e4e4ae0e030333_large.jpg', 2147483647, '978-604-2-33105-0', 140, 'Chow Hon Lam', 'Khác với tưởng tượng thường thấy về loài cá sấu, Buddy Gator lại là một chú cá sấu ấm áp và ngọt ngào. Cậu luôn sống tử tế, yêu thương mọi người xung quanh. Bởi thế, có lẽ tất cả chúng ta đều cần một người bạn như cậu ấy.\r\nNhững mẩu truyện tranh ngắn duyên dáng và hóm hỉnh của Chow Hon Lam đã ghi lại những khoảnh khắc của lòng tốt, của tình bạn, tình yêu, của sự tôn trọng và chia sẻ. Bộ sách nhỏ về chàng cá sấu thân thiện sẽ đem đến cho người đọc những cảm xúc tích cực – món quà hoàn hảo cho cả trẻ em và người lớn. '),
(51, 1, 'TÝ QUẬY - TẬP 11', '28000.0', 'https://product.hstatic.net/200000343865/product/11_bbddaefc79da421eadce8a320cd644b6_large.jpg', 2147483647, '978-604-2-29328-0', 184, 'Đào Hải', '“Tý quậy là một phần tuổi thơ tôi, của bạn bè tôi. Không có ý mong Tý trở thành nhân vật điển hình, tôi chỉ ước sao Tý quậy là một người bạn gần gũi, quen thuộc và sống đúng nghĩa tuổi thơ.\r\n\r\nThật không khôn ngoan khi dạy trẻ phải suy nghĩ những gì, mà nên hướng cho tuổi thơ cách suy nghĩ. Một đứa trẻ không hoạt bát thì tuyệt đối sẽ không trở thành người thông minh.\r\n\r\nCó câu danh ngôn rằng: việc độc nhất vô nhị và không có gì thay thế, đó là hồi ức về tuổi thơ. Vậy khi làm sách Tý quậy, bên cạnh tình yêu thương trong tôi có cả sự trân trọng...”\r\n\r\n                                                                                                (Tác giả Đào Hải)'),
(52, 1, 'TÝ QUẬY - TẬP 8', '28000.0', 'https://product.hstatic.net/200000343865/product/8_d74bf22c3b97418697b0832756fb33e7_large.jpg', 2147483647, '978-604-2-29325-9', 172, 'Đào Hải', '“ Tý Quậy là một phần tuổi thơ của tôi, của bạn bè tôi. Không có ý mong Tý trở thành nhân vật điển hình, tôi chỉ ước sao Tý quậy là một người bạn gần gũi, quen thuộc và sống với đúng nghĩa tuổi thơ. Thật không khôn ngoan khi dạy trẻ phải suy nghĩ những gì, mà nên hướng cho tuổi thơ cách suy nghĩ. Một đứa trẻ không hoạt bát thì tuyệt đối sẽ không trở thành người thông minh. Có câu danh ngôn rằng : Việc độc nhất vô nhị và không gì có thể thay thế, đó là hồi ức về tuổi thơ. Vậy khi làm sách Tý Quậy, bên cạnh tình yêu thương trong tôi có cả sự trân trọng… “ Những trò đùa vui học trò ai cũng đã từng kinh qua, những nghịch ngợm nho nhỏ trên đường trưởng thành… bạn đọc nhí sẽ cười nghiêng ngả, cha mẹ cũng bật cười : “ Sao Tý và Tèo giống mình ngày xưa quá vậy!” Sau những trận cười ấy, hẳn bạn sẽ nhận ra điều nhắn nhủ giản đơn mà sâu sắc của tác giả, giúp chúng ta  học hỏi và tiến bộ hơn sau mỗi tiếng cười vui vẻ.'),
(53, 1, 'TÝ QUẬY - TẬP 3', '28000.0', 'https://product.hstatic.net/200000343865/product/3_a388e52f907445b28d49cc9d709de491_large.jpg', 2147483647, '978-604-2-29320-4', 172, 'Đào Hải', '“ Tý Quậy là một phần tuổi thơ của tôi, của bạn bè tôi. Không có ý mong Tý trở thành nhân vật điển hình, tôi chỉ ước sao Tý quậy là một người bạn gần gũi, quen thuộc và sống với đúng nghĩa tuổi thơ. Thật không khôn ngoan khi dạy trẻ phải suy nghĩ những gì, mà nên hướng cho tuổi thơ cách suy nghĩ. Một đứa trẻ không hoạt bát thì tuyệt đối sẽ không trở thành người thông minh. Có câu danh ngôn rằng : Việc độc nhất vô nhị và không gì có thể thay thế, đó là hồi ức về tuổi thơ. Vậy khi làm sách Tý Quậy, bên cạnh tình yêu thương trong tôi có cả sự trân trọng… “ Những trò đùa vui học trò ai cũng đã từng kinh qua, những nghịch ngợm nho nhỏ trên đường trưởng thành… bạn đọc nhí sẽ cười nghiêng ngả, cha mẹ cũng bật cười : “ Sao Tý và Tèo giống mình ngày xưa quá vậy!” Sau những trận cười ấy, hẳn bạn sẽ nhận ra điều nhắn nhủ giản đơn mà sâu sắc của tác giả, giúp chúng ta  học hỏi và tiến bộ hơn sau mỗi tiếng cười vui vẻ.'),
(54, 1, 'HÔN NHÂN HẠNH PHÚC CỦA TÔI (LIGHT-NOVEL ) - TẬP 2', '90000.0', 'https://product.hstatic.net/200000343865/product/2----novel_b9764a0965cc456785a52def49ae9bac_large.jpg', 2147483647, '978-604-2-32904-0', 304, 'Akumi Agitogi', 'Miyo lớn lên trong cảnh bị mẹ kế ngược đãi tàn tệ, nay đã đính hôn với Kiyoka, một quân nhân nổi tiếng lạnh lùng. Ai ai cũng dự đoán về một kết cục đầy bất hạnh, nhưng không biết từ bao giờ, Kiyoka và Miyo lại cùng bị thu hút bởi sự dịu dàng của đối phương. \r\nMiyo mong muốn dù chỉ chút ít thôi cũng có thể bắt kịp Kiyoka mạnh mẽ và anh tuấn, bắt tay vào chăm chỉ học hành. Lấy mục tiêu là ra mắt chính thức tại buổi tiệc sau hai tháng nữa sẽ diễn ra, Miyo cũng tìm được niềm vui trong quãng thời gian nỗ lực phấn đấu này. Giữa bối cảnh đó, không hiểu vì sao mỗi đêm cô lại bị ác mộng giày vò. Không thể dựa dẫm vào ai, sức khoẻ Miyo trở nên suy yếu. Không chỉ có vậy, những kẻ nhắm đến Miyo đột nhiên xuất hiện, Miyo và Kiyoka không tìm được tiếng nói chung…\r\nĐây là câu chuyện về một thiếu nữ sẽ được yêu thương và trở nên hạnh phúc.\r\n* Hôn Nhân Hạnh Phúc Của Tôi là bộ truyện ăn khách của tác giả Akumi Agitogi, đến nay đã bán được hơn 6 triệu bản, được chuyển thể thành manga, anime và phim điện ảnh ra mắt năm 2023.\r\nSố tập: 7+ (on-going)'),
(55, 1, 'HÔN NHÂN HẠNH PHÚC CỦA TÔI (MANGA) - TẬP 3', '45000.0', 'https://product.hstatic.net/200000343865/product/3----manga_a09f4f9e885a402c83c2c844ac0f305a_large.jpg', 2147483647, '978-604-2-32903-3', 214, 'Akumi Agitogi', 'Lần đầu tiên biết đến “niềm hạnh phúc khi được yêu thương”…\r\nSaimori Miyo bẩm sinh không có dị năng, chẳng được ai cần tới, rồi bị đem gả vào nhà Kudou, cũng là một dòng tộc sở hữu dị năng, cho một người chồng tương lai nổi danh lạnh lùng tàn nhẫn.\r\nTuy nhiên, dáng vẻ khác xa các tiểu thư con nhà danh giá kiêu sa đài các của Miyo lại thu hút sự chú ý của gia chủ Kudou Kiyoka, và chẳng bao lâu sau, anh đã đem lòng cảm mến, trân trọng cô hết mực.\r\nVậy nhưng, đứa em gái cùng cha khác mẹ của Miyo ở nhà Saimori là Kaya nảy sinh lòng đố kị, bắt cóc Miyo đem nhốt vào nhà kho, rồi tuyên bố như thế này với ánh mắt ngập tràn điên loạn.\r\n“Chị hãy huỷ bỏ hôn ước cùng ngài Kudou và đổi vị hôn phu với tôi đi?”\r\nTrong khi đó, Kiyoka dùng sức mạnh của dị năng để tới giải cứu Miyo…\r\nMời các bạn đến với một thiên tình sử bắt đầu từ cuộc hôn nhân sắp đặt.\r\n* WINGS BOOKS - Thương hiệu sách trẻ của NXB Kim Đồng hân hạnh gửi đến các bạn độc giả phiên bản chuyển thể manga đặc sắc của bộ light-novel ăn khách Hôn Nhân Hạnh Phúc Của Tôi\r\nLoạt sách đến nay đã bán được hơn 6 triệu bản, được chuyển thể thành anime và phim điện ảnh ra mắt năm 2023.\r\nSố tập: 4+ (on-going)'),
(56, 1, 'CÔ NÀNG SHIMOTSUKI TRÓT PHẢI LÒNG NHÂN VẬT NỀN - TẬP 1', '80500.0', 'https://product.hstatic.net/200000343865/product/1---lmt_2b5363ec2d6646188a1356ae27d26a66_large.jpg', 2147483647, '978-604-2-32899-9', 308, 'Kagami Yagami', 'Tại sao cô bạn Shimotsuki không bao giờ cười ấy lại để ý đến tôi!?\r\nSau giờ học, khi Nakayama Koutarou quay lại trường để lấy một thứ mà cậu để quên, cậu tình cờ nhìn thấy Shimotsuki Shiho đang ngủ trong lớp học trống. Mọi người đồn rằng cô ấy là mối quan tâm lớn nhất của Ryuuzaki Ryouma, chàng trai nổi tiếng nhất lớp, nhưng cô ấy luôn trưng ra vẻ mặt vô cảm và chẳng bao giờ cười. \r\nVậy mà giờ đây, những ngón tay trắng nõn ấy đang nắm lấy bàn tay Koutarou…!?\r\n\"Mối quan hệ bí mật\" giữa nữ chính tóc bạch kim và chàng trai nhân vật nền đã bắt đầu nhờ một cơ duyên kì lạ.\r\nVà chuyện tình thanh xuân buồn tẻ của chàng trai nhân vật nền sẽ được “viết lại” bằng những chương hoa mộng mới!!\r\n* Cô Nàng Shimotsuki Trót Phải Lòng Nhân Vật Nền là series Light Novel “tân binh” của dòng Rom-Com, với chủ đề mới mẻ và cách xây dựng cốt truyện thú vị, đã được chuyển thể thành manga!'),
(57, 1, 'ẢO ẢNH VÀ TRO TÀN - TẬP 14 + & 14 ++', '140000.0', 'https://product.hstatic.net/200000343865/product/bx_b279d83f5aff408ca820a298a0e5ad0b_large.jpg', 2147483647, '0', 370, 'Ao Jyumonji', 'Trước khi đến với hồi cuối của cuộc phiêu lưu được sinh ra từ trong đám tro tàn, mời các bạn độc giả đón đọc một ấn phẩm đặc biệt, tập hợp những câu chuyện hoàn toàn mới theo chân hai nhân vật tách đội là Ranta và Yume, cũng như các tiểu thuyết đi kèm bản TV anime ôn lại một vài kỉ niệm từ những ngày đầu.\r\nGrimgar - Ảo ảnh và tro tàn - Level.14+ - Không thể không thay đổi\r\nKhi nhóm Haruhiro đang lạc bước đến Thế giới bên kia Parano, ở Grimgar đã xảy ra sự thay đổi không tưởng… Trong thế giới đầy biến động, anh chàng đó giấu đi khuôn mặt thật đằng sau chiếc mặt nạ, đơn độc hướng tới Alterna…\r\n“Mình có đang nghe theo con tim của bản thân không…? Nếu là vậy thì chẳng có vấn đề gì cả.”\r\nCuốn sách tập hợp tổng cộng bốn chương truyện, bao gồm chương “Mặt nạ hữu tình” viết mới hoàn toàn, khắc hoạ cuộc chiến đấu gian khổ của Ranta khi tiếp tục hành trình, bên cạnh đó có cả tiểu thuyết đặc biệt đi kèm bản TV anime, như chương “Làm ơn, chỉ một chút nữa thôi” thể hiện nỗi lòng của Manato, người lính tình nguyện tập sự đã chết khi vẫn còn nuối tiếc, chương “Hôm nay nghỉ thôi” tái hiện cuộc giao lưu với các vị sư phụ mà Shihoru và Yume đã gặp gỡ ở guild…!\r\nGrimgar - Ảo ảnh và tro tàn Level.14++ - Nếu ta có thể gặp lại nhau\r\nYume rời tổ đội để đồng hành cùng Momohina trên con đường tu luyện. Sau khi vượt qua những tình huống hiểm nghèo, cô đã quay lại Alterna. Thế nhưng, tình trạng có gì đó thật kì lạ. Liệu cô có thể tái ngộ với đồng đội hay không? Đám mây đen u ám lơ lửng phía trên Alterna thực chất là gì…?\r\n“Yume yếu ớt không còn lựa chọn nào khác ngoài cố gắng cho đến khi mạnh lên.”\r\nCuốn sách tập hợp tổng cộng bốn chương truyện, bao gồm chương “Tôi là sói, hú lên dưới trăng” vẽ nên sự trưởng thành cùng quyết tâm của Yume sau khi kết thúc tu luyện, bên cạnh đó có cả tiểu thuyết đặc biệt đi kèm bản TV anime, như chương “Chính nghĩa cùng chính nghĩa”, kể lại lần Ranta liều lĩnh khiêu chiến nấu ăn với Moguzou, chương “Chuyện hay còn ở đằng sau” là phần tiếp theo xoay quanh việc chia tiền thưởng cả bọn kiếm được từ việc hạ gục Dead Spot…'),
(58, 1, 'CON TRAI TÔI HÌNH NHƯ LÀ GAY - TẬP 5', '30600.0', 'https://product.hstatic.net/200000343865/product/5_3a48cc8653544d1789bc6e841c714c8f_large.jpg', 2147483647, '978-604-2-33151-7', 130, 'Okura', 'Tôi tên Tomoko, bình thường tôi sống cùng hai con trai. Tôi nghĩ đứa lớn Hiroki nhà mình có thể là gay. Hằng ngày Hiroki vẫn sinh hoạt câu lạc bộ cùng cậu bạn Daigo nó rất thích, dạo gần đây hai đứa còn tập nhảy nữa. Mà hình như có chuyện gì đó đã xảy ra giữa Hiroki và cô bé Asumi khoá dưới thầm mến thằng bé thì phải…?\r\nĐúng lúc này, người chồng đi làm xa của tôi quay về, gia đình bốn người chúng tôi lại cùng nhau chung sống. Trong thế giới xoay vần đến chóng mặt, các con trai tôi đang ngày một trưởng thành. Là một người mẹ, tôi băn khoăn không biết nên đối xử với chúng ra sao. Liệu tôi có nên can thiệp thay vì chỉ đứng nhìn như trước?\r\n“Con trai tôi hình như là gay. Dù sự thật có phải là vậy hay không thì tôi vẫn mong cậu con trai đáng yêu của mình được hạnh phúc.”\r\nĐây là tập 5 và cũng là tập cuối cùng câu chuyện của người mẹ luôn hướng về gia đình mình với ánh mắt ngập tràn tình yêu thương.'),
(59, 1, 'ANIMATION ARTIST - VÉN MÀN HẬU TRƯỜNG CỦA NHỮNG BƯỚC CHÂN 4.0', '120000.0', 'https://product.hstatic.net/200000343865/product/animation-artist---ven-man-hau-truong_6658411082f64bd89d4d0ec33de464a4_large.jpg', 2147483647, '978-604-2-28307-6', 244, 'DeeDee Animation Studio', 'Kỉ nguyên 4.0 đã tạo ra những thay đổi sâu rộng trong sản xuất và đời sống, đặc biệt có những tác động không nhỏ đến sự chuyển dịch của các ngành nghề trong xã hội. Đứng trước các cơ hội lựa chọn nghề nghiệp phong phú, làm thế nào để người Việt trẻ có thể bắt kịp thời đại, khai mở những tiềm năng nội tại, xây dựng “thương hiệu cá nhân” giữa vòng xoáy cạnh tranh khốc liệt của thị trường lao động, và có được sự lựa chọn thấu đáo trên con đường lập thân lập nghiệp?\r\nBộ sách này sẽ cùng bạn đọc theo dấu các chuyên gia trong từng lĩnh vực để “vén màn” hậu trường của những ngành nghề đang phát triển mạnh mẽ trong thời đại 4.0, giúp bạn hiểu nghề để làm nghề một cách thuận lợi. Khi đã nắm vững “bản đồ nghề nghiệp” trong tay, bạn sẽ có được sự lựa chọn đúng đắn cho tương lai, sẵn sàng tạo ra những bước nhảy vọt cho bản thân để thành công hơn trong mỗi nghề nghiệp mình lựa chọn.\r\nANIMATION ARTIST LÀ CÁC HOẠ SĨ/CHUYÊN GIA THỰC HIỆN VIỆC THIẾT KẾ VÀ PHÁT TRIỂN MỘT BỘ PHIM HOẠT HÌNH.\r\nNhững điều thú vị bạn sẽ khám phá trong cuốn sách Animation Artist này là:\r\n√ Lịch sử và tương lai của ngành hoạt hình trên thế giới và tại Việt Nam.\r\n√ Những nghệ sĩ phụ trách các bước trong quá trình tạo nên một tác phẩm hoạt hình.\r\n√ Kĩ năng sử dụng các công cụ sáng tạo hoạt hình.\r\n√ Học cách làm hoạt hình tại đâu và các bước chinh phục nhà tuyển dụng. \r\nDeeDee Animation Studio là studio hoạt hình 2D tiêu chuẩn quốc tế, với các chi nhánh tại Hà Nội và TP. Hồ Chí Minh. DeeDee đã hợp tác sản xuất với các studio hoạt hình hàng đầu thế giới như Walt Disney Animation, Shin-Ei Animation, TMS Entertainment, 6 Point Harness.'),
(60, 1, 'CHITOSE TRONG CHAI RAMUNE - TẬP 4', '115000.0', 'https://product.hstatic.net/200000343865/product/4---obi_68bfb47b6da54f06812d16480faa41d1_large.jpg', 2147483647, '978-604-2-32023-8', 520, 'Hiromu', 'Tháng Bảy, sau khi vòng loại Giải vô địch bóng rổ trung học kết thúc. Haru đã trở thành đội trưởng mới của đội bóng rổ nữ. Đón chờ cô ấy là những tháng ngày vừa cạnh tranh lành mạnh với các đồng đội, vừa dốc sức rèn giũa bản thân để cùng nhau hướng tới đỉnh cao. Hình bóng của cô ấy như tỏa ra ánh hào quang sáng chói làm trái tim tôi dao động. Giữa lúc ấy, thủ lĩnh đội bóng chày, Ezaki bỗng xuất hiện.\r\n“Xin cậu đấy, hãy về đội đi.”\r\n... Chính vào ngày hè nóng bức ấy. Chiếc đồng hồ tôi đã tự tay cho ngừng lại liền cất tiếng và hoạt động trở lại.\r\nĐây là câu chuyện về một lần đổ vỡ, về những giằng xé nội tâm, cùng tinh thần “nhiệt huyết” tới giờ vẫn còn âm ỉ cháy trong tôi.\r\nCâu chuyện về cách mà tôi đã khép lại ngày hè năm đó và mở ra một mùa hè hoàn toàn mới.'),
(61, 1, 'CHÚA TỂ BÓNG TỐI (LIGHT-NOVEL) - TẬP 1', '128000.0', 'https://product.hstatic.net/200000343865/product/1---lmt_c6192d87264a4ed8b015befdb10e4379_large.jpg', 2147483647, '978-604-2-32013-9', 422, 'Daisuke Aizawa', '“Tên ta là Shadow. Ta ẩn mình trong bóng tối để săn lùng bóng tối…”\r\nKhông phải nhân vật chính, cũng chẳng phải trùm cuối. Ấy là những Chúa tể Bóng tối, bình thường thì che giấu thực lực, giả làm người thường, nhưng trong bóng tối lại thể hiện sức mạnh thực sự của mình để bí mật can thiệp vào câu chuyện. Cậu thiếu niên ngưỡng mộ Chúa tể Bóng tối của chúng ta ngày ngày rèn luyện trau dồi sức mạnh, đồng thời vẫn đóng vai một nhân vật quần chúng mờ nhạt trước mặt người đời, cho đến khi gặp tai nạn và được chuyển sinh sang một thế giới khác.\r\nVui sướng trước tình cảnh này, cậu thiếu niên, giờ mang tên Cid, đã quyết định “tưởng tượng” ra một “Giáo phái bóng tối” để (giả vờ) bí mật lật đổ, thoả mãn mong muốn đóng vai Chúa tể Bóng tối ở thế giới mới. Thế nhưng không ngờ “Giáo phái bóng tối” ấy lại có thật…?\r\nDo không ít hiểu lầm mà những cô gái trở thành thuộc hạ của Cid đều sùng bái cậu, và chính bản thân Cid cũng không biết cậu đã trở thành một Chúa tể Bóng tối thực sự, tổ chức bóng đêm Shadow Garden do cậu đứng đầu đang dần tiêu diệt màn đêm che phủ thế giới…');
INSERT INTO `product` (`id_product`, `id_catalog`, `productName`, `price`, `image_link`, `productCode`, `ISBN`, `pageNumber`, `author`, `content`) VALUES
(62, 1, 'NHÂN VẬT HẠ CẤP TOMOZAKI - TẬP 5', '110000.0', 'https://product.hstatic.net/200000343865/product/5---lmt_a3a410a4533a4e45a524468941d27ae8_large.jpg', 2147483647, '978-604-2-32015-3', 424, 'Yuki Yaku', 'Sau một vụ việc xảy ra ở lớp, không ngờ giữa tôi và nhóc Tama lại hình thành mối quan hệ thầy trò. Nét mặt, tác phong, cách nói chuyện. Với tư cách sư phụ, tôi truyền thụ cho nhóc Tama những bí quyết và nỗ lực mình đã tích luỹ để trở thành riajuu. Mặt khác, với tính cách vốn có của mình, Hinami đang âm thầm hành động... Đối mặt với vấn đề bằng lối suy nghĩ trái ngược nhau, quả nhiên chúng tôi không thể hợp tác. Dù vậy, “nếu là để đạt được mục đích quan trọng, tôi sẵn sàng thay đổi chính mình”. \r\nChắc chắn một người nào đó đã dạy tôi cách chiến đấu này.'),
(63, 1, 'PHÒNG THIẾT KẾ KHAI THIÊN LẬP ĐỊA - TẬP 3', '36000.0', 'https://product.hstatic.net/200000343865/product/3_33464efdb7194de391d46515fe795ec2_large.jpg', 2147483647, '978-604-2-32019-1', 144, 'Hebi-zou', 'Chim ong ngủ thì sẽ chết!?\r\n“Phòng Thiết kế” động vật trên Thiên giới mỗi ngày đều phải thiết kế ra rất nhiều động vật theo các yêu cầu oái ăm của Thượng đế. “Có sinh vật nào tạo ra được đá quý không?” “Rái cá biển làm thế nào có thể ngủ ở biển?” “Tại sao sư tử đực lại có bờm?” \r\nCác bạn sẽ tìm thấy vô vàn thông tin vừa hay ho vừa bổ ích trong bộ truyện hết sức hài hước này!! Đừng quên là chúng ta luôn có “Từ điển hình ảnh các sinh vật” vô cùng được yêu thích nhé!'),
(64, 1, 'ẨM THỰC CHINH PHỤC THẾ GIỚI - CHOCOLATE', '55000.0', 'https://product.hstatic.net/200000343865/product/am-thuc-chinh-phuc-the-gioi-_chocolate_bia_c10bc273becf4604a9f71955679d93f4_large.jpg', 2147483647, '978-604-2-32020-7', 104, 'Bảo Anh', 'Trải qua mấy ngàn năm, chúng ta đã biết đến một trong những nguyên liệu có hương vị quyến rũ, làm mê đắm lòng người nhất trong nền ẩm thực nói chung và ngành đồ ngọt nói riêng, mang tên chocolate. Niềm yêu thích chocolate từ châu Mĩ, châu Âu đã lan ra thế giới nhanh hơn bất kì loại thực phẩm nào. Cacao được ví như một sản vật đến từ “thiên đường”, nhưng bằng chính sự sáng tạo của mình, con người đã biến chocolate trở thành món quà có giá trị vàng.\r\nCuốn sách này sẽ cùng bạn khám phá hành trình chinh phục thế giới đầy li kì và hấp dẫn của chocolate!\r\n“Khi nếm những thanh chocolate thơm ngon, chúng ta rất dễ liên tưởng đến những gì lãng mạn nhất. Đường phố châu Âu với những quầy đồ ngọt lấp lánh. Những món quà ngọt ngào không thể thiếu vị chocolate. Nhưng liệu có mấy ai hiểu về ‘vị đắng’ của chocolate. Và những mặt trái của ngành công nghiệp đồ ngọt lớn nhất thế giới này?”'),
(65, 1, 'LIỆU CÓ SAI LẦM KHI TÌM KIẾM CUỘC GẶP GỠ ĐỊNH MỆNH TRONG DUNGEON', '150000.0', 'https://product.hstatic.net/200000343865/product/11---lmt_e818eac6e3c6405c990cff9f83e29cc0_large.jpg', 2147483647, '978-604-2-28305-2', 528, 'Fujino Omori', 'Danh tiếng của Little Rookie đã rớt xuống đáy vực. Bell đã đánh mất niềm tin của mọi người khi lựa chọn giải cứu Wiene. Bị bủa vây giữa ác ý và thất vọng, cậu đau khổ và rối bời. Tuy nhiên…\r\n“Đừng lưỡng lự. Xung quanh cậu vẫn còn những thứ không thể để mất.”\r\nĐược các mối quan hệ từ những cuộc gặp gỡ định mệnh tương trợ, Bell đặt ra quyết tâm mới và đứng lên cùng các đồng đội. Kế hoạch đưa các Xenos trở về Dungeon được khởi động giữa thành phố mê cung lại một lần nữa trở thành chiến trường. Cản đường họ là phe phái hùng mạnh nhất thành phố – Loki familia. Trí tuệ của hiền giả, kế hoạch của Braver, suy đoán của thần linh, và khi con quái thú đen gầm lên, trái tim của cậu thiếu niên trở lại.\r\n“Tôi... muốn mạnh lên.”\r\nĐây là câu chuyện do cậu thiếu niên tạo, nữ thần viết.'),
(66, 1, 'LIỆU CÓ SAI LẦM KHI TÌM KIẾM CUỘC GẶP GỠ ĐỊNH MỆNH TRONG DUNGEON', '120000.0', 'https://product.hstatic.net/200000343865/product/10_fe1fee197f854360b2690c529cd7786a_large.jpg', 2147483647, '978-604-2-27334-3', 500, 'Fujino Omori', 'Ngay sau khi làm quen được với nhóm quái vật có trí tuệ Xenos, Bell đã phải chia tay Wiene. Kể từ đó mỗi ngày của Bell trôi qua trong sầu muộn, còn Wiene thì vẫn luôn bị nguy hiểm rình rập. Và rồi…\r\n“Phát hiện quái vật có vũ trang đang đồng loạt di chuyển! Hội ra lệnh xuất quân chinh phạt rồi!!”\r\nChuyện nhóm Xenos nổi dậy tấn công đã khiến sự việc không thể vãn hồi. Kẻ chịu trách nhiệm không ai khác chính là đám thợ săn hung ác, và kết quả là toàn bộ các familia khác bị cuốn theo, thành phố rơi vào cảnh hỗn loạn. \r\nĐối mặt với phong ba bão táp trước mắt, cậu thiếu niên buộc phải đưa ra quyết định.\r\nKhát vọng của bản thân hay quái vật, hiện thực hay lí tưởng, anh hùng hay tội nhân.\r\nĐứng giữa hai phe là nhân loại và quái vật, Bell sẽ… \r\n“Cậu thật sự khờ quá…”\r\nĐây là câu chuyện do cậu thiếu niên tạo, nữ thần viết.'),
(67, 1, 'LIỆU CÓ SAI LẦM KHI TÌM KIẾM CUỘC GẶP GỠ ĐỊNH MỆNH TRONG DUNGEON', '105000.0', 'https://product.hstatic.net/200000343865/product/9_b4fd9c4706074654b5995b9800cae1ef_large.jpg', 2147483647, '978-604-2-23860-1', 426, 'Fujino Omori', '“Quái vật... Vouivre?” \r\n\r\nBell tình cờ bắt gặp cô bé quái vật rồng tên Wiene khi tiến vào khu vực mới trong Dungeon – Mê Cung Đại Thụ. Cô bé nói được ngôn ngữ loài người, cô độc một mình vì bị cả con người lẫn những quái vật khác truy sát. Cậu thiếu niên tóc trắng quyết định sẽ che chở cho Wiene nhưng… \r\n\r\n“Vouivre sao… tuyệt phẩm lâu rồi mới xuất hiện đấy.”\r\n\r\nThủ đoạn của đám thợ săn hung ác đang lén lút rình rập, mối quan hệ tồi tệ đến không thể vãn hồi giữa con người và quái vật, động thái của người thật sự đứng sau Hội. Cả thành phố trở nên náo loạn vì sự xuất hiện của cô nhóc Vouivre. Hiện Tượng Bất Thường làm rung chuyển cả loài người, quái vật và các vị thần. Những bí mật ẩn trong Dungeon bắt đầu được hé mở…? \r\n\r\n“Em thích… Bell lắm.” \r\n\r\nĐây là câu chuyện do cậu thiếu niên tạo, nữ thần viết.'),
(68, 1, 'LIỆU CÓ SAI LẦM KHI TÌM KIẾM CUỘC GẶP GỠ ĐỊNH MỆNH TRONG DUNGEON', '150000.0', 'https://product.hstatic.net/200000343865/product/8_28d38e6178f643c7a22e879d46caca46_large.jpg', 2147483647, '978-604-2-21861-0', 652, 'Fujino Omori', 'Quân đội Rakia xuất binh.\r\n\r\nCuộc tấn công đầy bất ngờ của quân đội vương quốc do Thần Chiến Tranh Ares cai trị. Ba mươi nghìn quân đang chĩa mũi lao nhọn hoắt về phía thành phố mê cung. Trước cả ngàn tiếng bước chân rầm rập kéo tới, Orario… vẫn bình thường như không có gì xảy ra.\r\n\r\nTrong lúc phía ngoài tường thành, tiếng thét gào của đoàn quân xâm lược bị các mạo hiểm giả hùng mạnh đánh “không trượt phát nào” thấu tận mây xanh, thì ở Orario, chuỗi ngày bình yên vẫn tiếp diễn. Lời cầu hôn của Pallum, chàng vệ sĩ ưa thích, bí mật của cô gái thành thị, khúc tình ca dâng tặng thần linh… và cả, bài hát tình yêu do nữ thần dệt nên. Lần này là tuyển tập những câu chuyện thường nhật bình dị của thần linh và những đứa trẻ!\r\n\r\n“Nhóc Bell, ta sẽ mãi mãi ở bên cậu.”\r\n\r\nĐây là câu chuyện do cậu thiếu niên tạo, nữ thần viết.'),
(69, 1, 'LIỆU CÓ SAI LẦM KHI TÌM KIẾM CUỘC GẶP GỠ ĐỊNH MỆNH TRONG DUNGEON', '150000.0', 'https://product.hstatic.net/200000343865/product/7_8d18fdf7fc2d411cb5aec405f7548065_large.jpg', 2147483647, '978-604-2-23874-8', 632, 'Fujino Omori', 'Dungeon không phải lúc nào cũng là nơi tăm tối nhất!\r\n\r\nSau trận War Game, Hestia familia thu nhận thêm ba thành viên mới là Lili, Welf và Mikoto. Giờ họ đã trở thành gia đình thứ hai của Bell, gắn kết sâu sắc với cậu. Hestia familia non trẻ bắt đầu có những bước tiến đầu tiên! \r\n\r\nTrong lúc đuổi theo Mikoto tới khu giải trí của Orario, Bell lạc vào khu phố đêm nằm dưới quyền quản lí của Ishtar familia. Tại nơi này, cậu thiếu niên tình cờ gặp thiếu nữ tên Haruhime xuất thân vùng Viễn Đông đang bị giam cầm. \r\n\r\nBị cuốn vào vòng xoáy âm mưu hiểm độc giữa các nữ thần, Bell buộc phải đưa ra sự lựa chọn. Với cậu, “anh hùng” thật sự là như thế nào?\r\n\r\n“Nếu cậu trở thành anh hùng của cô ấy thì mọi chuyện sẽ ổn thôi, phải không?”\r\n\r\nĐây là câu chuyện do cậu thiếu niên tạo, nữ thần viết.'),
(70, 1, 'DƯỢC SƯ TỰ SỰ (MANGA) - TẬP 8', '47000.0', 'https://product.hstatic.net/200000343865/product/8_d6f1b82a0ab54b47b860068f76885f69_large.jpg', 2147483647, '978-604-2-31327-8', 178, 'Natsu Hyuuga', 'La Hán thua một ván cờ tướng khi đấu với Miêu Miêu, phải uống rượu phạt và say bí tỉ. Trong mơ, ông ta nhớ về những chuyện xảy ra với người kĩ nữ năm xưa và cuộc gặp gỡ cùng con gái. Và rồi, sau khi La Hán tỉnh lại ở Lục Thanh quán, ai sẽ là kĩ nữ mà ông ta lựa chọn chuộc thân...?\r\nTập 8 mở ra với phân đoạn cao trào trong tập 2 tiểu thuyết nguyên tác, hé lộ bí mật về sự ra đời của Miêu Miêu...'),
(71, 1, 'DƯỢC SƯ TỰ SỰ (MANGA) - TẬP 7', '47000.0', 'https://product.hstatic.net/200000343865/product/7_8ba09b4bdbdb47c296649b73945522ae_large.jpg', 2147483647, '978-604-2-31326-1 ', 182, 'Natsu Hyuuga', 'Sau khi cứu Nhâm Thị khỏi hiểm nguy, Miêu Miêu bắt đầu vạch trần bản chất của những sự cố mang vỏ bọc ngẫu nhiên. Toàn bộ chân tướng của vụ án sau khi đã được làm sáng tỏ là như thế nào? Mọi suy luận đều dẫn đến một nữ quan cùng một kết cục không ngờ tới...\r\nTrong tập 7 này, xuất phát từ một yêu cầu nan giải “muốn ngắm hoa hồng xanh”, Miêu Miêu cũng buộc phải đối mặt với La Hán...'),
(72, 1, 'DƯỢC SƯ TỰ SỰ (MANGA) - TẬP 2', '47000.0', 'https://product.hstatic.net/200000343865/product/2_4532de8990964ee586c7252a12e3a8f4_large.jpg', 2147483647, '978-604-2-31321-6', 178, 'Natsu Hyuuga', 'Miêu Miêu trước đây vốn là một dược sư, sau khi bị hoạn quan Nhâm Thị phát hiện ra tài năng, cô đã trở thành thị nữ của vị phi tần có tên là Ngọc Diệp. Cô nhận một mệnh lệnh trực tiếp từ “Hoàng đế”, nhưng công việc mà cô được uỷ thác ấy rốt cuộc là gì...!?\r\nTrong tập thứ 2 này, Miêu Miêu cũng hoạt động vô cùng tích cực!! Bị thôi thúc bởi niềm khát khao tri thức và tính hiếu kì cố hữu, cô bất ngờ thu hút sự chú ý của tất cả mọi người!!'),
(73, 1, 'DƯỢC SƯ TỰ SỰ (MANGA) - TẬP 1', '47000.0', 'https://product.hstatic.net/200000343865/product/1_3b78089d1ed44ed585bd6b8c005e949f_large.jpg', 2147483647, '978-604-2-31320-9', 178, 'Natsu Hyuuga', 'Miêu Miêu là một cô gái làm công việc hầu hạ trong cung đình thời phong kiến.\r\nCâu chuyện của chúng ta bắt đầu với việc cô gái từng hành nghề dược sư ở phố hoa này nghe thấy người ta đồn thổi rằng: tất cả những đứa con của Hoàng đế đều đoản mệnh.\r\nBị thúc đẩy bởi niềm khát khao tri thức và tính hiếu kì cố hữu, Miêu Miêu bắt tay vào tìm hiểu nguyên nhân, xem đó như một cách giải khuây không hơn không kém.'),
(74, 1, 'TRƯỜNG CA ACHILLES', '156000.0', 'https://product.hstatic.net/200000343865/product/truong-ca-achilles_bia-va-obi-1_c4dfa5ecfddd4480a3ba97da53391f00_large.jpg', 2147483647, '978-604-2-31313-1 ', 444, 'Madeline Miller', 'Hy Lạp vào thời hoàng kim của các anh hùng. Patroclus là một hoàng tử trẻ vụng về, bị trục xuất tới vương quốc Phthia và được nuôi dạy dưới sự che chở của vua Peleus cùng cậu con trai hoàng kim của ngài, Achilles. “Người Hy Lạp vĩ đại nhất” – mạnh mẽ, đẹp đẽ, và mang nửa dòng máu của một nữ thần – Achilles là tất cả những gì mà Patroclus không bao giờ có được. Nhưng bất chấp sự khác biệt giữa họ, hai cậu bé trở thành chiến hữu trung thành của nhau. Tình cảm giữa họ càng đậm sâu khi cả hai lớn lên thành những chàng trai trẻ, thành thạo trong kĩ nghệ chiến đấu và y dược.\r\n\r\nKhi tin tức truyền tới rằng nàng Helen xứ Sparta đã bị bắt cóc, những chiến binh Hy Lạp, bị trói buộc bởi lời thề máu, phải nhân danh nàng mà vây hãm thành Troy. Bị cám dỗ bởi lời hứa hẹn về một số mệnh huy hoàng, Achilles tham gia hàng ngũ của họ. Bị giằng xé giữa tình yêu và nỗi lo sợ dành cho người bạn của mình, Patroclus ra trận theo Achilles. Họ không hay biết rằng các nữ thần Số Phận sẽ thử thách cả hai người họ hơn bao giờ hết và đòi hỏi một sự hi sinh khủng khiếp.\r\n\r\nDựa trên nền tảng của sử thi Iliad, câu chuyện về cuộc chiến thành Troy vĩ đại đã được Madeline Miller kể lại với tiết tấu dồn dập, lôi cuốn, và không kém phần xúc động, đánh dấu sự khởi đầu của một sự nghiệp rực rỡ.'),
(75, 1, 'CẢM XÚC KHÔNG PHẢI ĐẶC QUYỀN - SỐNG MỘT LẦN VÌ CHÍNH MÌNH', '68000.0', 'https://product.hstatic.net/200000343865/product/song-mot-lan-vi-chinh-minh_bia_b3de55be9c2d4c3e840f01f142f192bb_large.jpg', 2147483647, '978-604-2-32024-5', 240, 'Thái Khang Vĩnh', 'Trong nội tâm mỗi người đều có vô vàn cảm xúc, nhưng tại sao có người bình tĩnh, cân bằng, lại có người bất an, bấn loạn?\r\nBởi vì có người biết tự học hỏi trau dồi, cùng với quá trình trưởng thành, để nhận biết được những cảm xúc đó, điều khiển cảm xúc đó phục vụ cho chính mình; có người lại nghĩ nó là đặc quyền có sẵn, cứ thế mà sử dụng, không cần biết nó đến từ đâu và nó rời đi như thế nào. \r\nNhận biết cảm xúc của bản thân giúp làm chính mình và khiến mối quan hệ nhân sinh trở nên phong phú. Quá trình học hỏi ấy có thể kéo dài cả một đời người, nhọc nhằn nhưng vô cùng đáng giá. Bạn không cần phải vội vã, hãy cứ từ từ từng bước một. Và bước đầu tiên trong tất cả các bước, hãy coi cảm xúc không phải đặc quyền!\r\n---\r\n“Ngu Công không chịu nổi ngọn núi lớn chặn trước cửa nhà, ông quyết định xúc từng xẻng đất để dịch chuyển quả núi ấy đi, chứ không phải dịch chuyển chính mình.\r\nNếu Ngu Công lúc đó đồng ý dịch chuyển bản thân, thậm chí chỉ cần dịch chuyển ý niệm, vậy thì ngọn núi trong mắt ông sẽ lập tức không còn là chướng ngại vật, mà sẽ biến thành một thế giới đáng để tìm hiểu, một phong cảnh đáng để thưởng lãm.\r\nCuốn sách này chính là muốn kể bạn nghe câu chuyện ấy.\r\nĐể núi là núi, để ta là ta. Không phải là ta do người khác nhào nặn ra, mà là ta do ta tạo dựng.\r\nHãy bắt đầu từ nội tâm, bởi đó là điều đáng giá nhất.”'),
(76, 1, 'THIÊN SỨ NHÀ BÊN - TẬP 6', '95000.0', 'https://product.hstatic.net/200000343865/product/6_790534efc1964030826d872a72be45fc_large.jpg', 2147483647, '978-604-2-32022-1', 324, 'Saekisan', 'Nhờ có Mahiru luôn ở bên, Amane đã dũng cảm đối diện với những hồi ức đau khổ trong quá khứ. Trong chuyến về thăm nhà bố mẹ Amane, khi cảm nhận được sự chăm sóc, quan tâm và tình cảm ấm áp từ gia đình, Mahiru thấy rất hạnh phúc. Ngắm nhìn cô với nụ cười chan chứa yêu thương, Amane một lần nữa củng cố quyết tâm sẽ luôn ở bên chăm sóc cô. \r\nVào những ngày cuối mùa hè, cả hai đã cùng mặc yukata đến lễ hội pháo hoa. Dù thật chậm rãi, nhưng cả Amane và Mahiru đều dần biết cách thể hiện cảm xúc của mình một cách thẳng thắn hơn, khiến những kí ức mùa hè của họ càng trở nên sâu sắc.\r\nĐây là câu chuyện tình ngọt ngào với cô gái nhà bên tuy lạnh lùng nhưng thật đáng yêu đã được ủng hộ nhiệt tình trên trang Shousetsuka ni Narou.'),
(77, 1, 'THIÊN SỨ NHÀ BÊN - TẬP 1', '95000.0', 'https://product.hstatic.net/200000343865/product/1_8cba7fafdfea4093993751bcc5edf4d9_large.jpg', 2147483647, '978-604-2-31328-5', 328, 'Saekisan', 'Hàng xóm kế bên căn hộ của Fujimiya Amane chính là nữ sinh xinh đẹp nhất trường cậu, Shiina Mahiru.\r\nHọ vốn chẳng có mối liên hệ nào cho đến một ngày mưa tầm tã, Amane tình nguyện đưa chiếc ô của mình cho cô bạn hàng xóm xinh đẹp tựa thiên thần, cả hai đã bắt đầu tương tác với nhau theo một cách kì quặc.\r\nChẳng thể chịu được lối sinh hoạt cẩu thả khi sống một mình của Amane, Mahiru đã quyết định sẽ chăm sóc cậu từ những điều nhỏ nhất.   \r\nMột Mahiru thiếu thốn sự gắn kết với gia đình đang dần mở lòng hơn, cùng một Amane hay tự ti đang ngày một đổi thay theo chiều hướng tích cực. Khoảng cách giữa hai con người không chút thành thật ấy đang từng bước thu hẹp lại...\r\nĐây là câu chuyện tình ngọt ngào với cô gái nhà bên tuy lạnh lùng nhưng thật đáng yêu đã được ủng hộ nhiệt tình trên trang Shousetsuka ni Narou. '),
(78, 1, 'THIÊN SỨ NHÀ BÊN - TẬP 2', '95000.0', 'https://product.hstatic.net/200000343865/product/2_e1024f83f82d47a69c7116dcf85eb537_large.jpg', 2147483647, '978-604-2-31329-2', 332, 'Saekisan', 'Amane là một nam sinh khá cẩu thả, còn Mahiru là nữ sinh xinh xắn nhất trường với biệt danh “thiên sứ”. Cả hai vốn chẳng có mối liên hệ nào với nhau, thế nhưng sau một dịp tình cờ, họ đã bắt đầu qua lại và ăn cơm chung một nhà.\r\n\r\nCùng nhau đón năm mới, đi chùa đầu năm, tránh khỏi những rắc rối của ngày Valentine... Nhờ những hành động tuy vụng về nhưng ấm áp của Amane, sự gặp gỡ với bố mẹ và bạn bè của Amane, trái tim băng giá của Mahiru dần tan chảy...\r\n\r\nĐây là câu chuyện tình ngọt ngào với cô gái nhà bên tuy lạnh lùng nhưng thật đáng yêu đã được ủng hộ nhiệt tình trên trang Shousetsuka ni Narou.'),
(79, 1, 'THIÊN SỨ NHÀ BÊN - TẬP 3', '95000.0', 'https://product.hstatic.net/200000343865/product/3_c71184a9cc0d42dd9dab2140014e882d_large.jpg', 2147483647, '978-604-2-26894-3', 324, 'Saekisan', 'Amane là một nam sinh khá cẩu thả, còn Mahiru là nữ sinh xinh xắn nhất trường với biệt danh “thiên sứ”. Cả hai vốn chẳng có mối liên hệ nào với nhau, thế nhưng sau một dịp tình cờ, họ đã bắt đầu qua lại và ăn cơm chung một nhà.\r\n\r\nCùng nhau đón năm mới, đi chùa đầu năm, tránh khỏi những rắc rối của ngày Valentine... Nhờ những hành động tuy vụng về nhưng ấm áp của Amane, sự gặp gỡ với bố mẹ và bạn bè của Amane, trái tim băng giá của Mahiru dần tan chảy...\r\n\r\nĐây là câu chuyện tình ngọt ngào với cô gái nhà bên tuy lạnh lùng nhưng thật đáng yêu đã được ủng hộ nhiệt tình trên trang Shousetsuka ni Narou.'),
(80, 1, 'THIÊN SỨ NHÀ BÊN - TẬP 4', '95000.0', 'https://product.hstatic.net/200000343865/product/4_be0025c5d9ea4206ab2c6167128a3883_large.jpg', 2147483647, '978-604-2-31331-5', 340, 'Saekisan', '“Đối với tôi... cậu ấy là người quan trọng nhất.”\r\n\r\nTrong khi cả lớp náo loạn vì phát ngôn gây sốc ấy của Mahiru thì Amane - người không thể đoán định được suy nghĩ của cô - đã quyết tâm trở thành chàng trai xứng đáng ở bên cạnh cô ấy.\r\n\r\nĐể theo kịp Mahiru, cô gái xinh đẹp, thông minh, hoàn hảo và luôn dành sự tin tưởng cho cậu, Amane đang rất phấn đấu trong cả chuyện học hành lẫn rèn luyện thể thao. Chẳng rõ Mahiru có hiểu cho tâm ý của Amane hay không, nhưng chính Mahiru cũng đang cố gắng tiến thêm một bước để xoay chuyển trạng thái mơ hồ trong mối quan hệ của hai người.\r\n\r\nĐây là câu chuyện tình ngọt ngào với cô gái nhà bên tuy lạnh lùng nhưng thật đáng yêu đã được ủng hộ nhiệt tình trên trang Shousetsuka ni Narou.'),
(81, 1, 'THIÊN SỨ NHÀ BÊN - TẬP 5', '95000.0', 'https://product.hstatic.net/200000343865/product/4_be0025c5d9ea4206ab2c6167128a3883_large.jpg', 2147483647, '978-604-2-31332-2', 344, 'Saekisan', 'Cùng trải qua biết bao vui buồn, Amane và Mahiru đã nhận ra tình cảm sâu sắc họ dành cho nhau. Mối quan hệ giữa nàng thiên sứ và chàng trai nhà bên đã bước sang một giai đoạn mới. Đều là “tình đầu” của nhau nên họ không tránh khỏi có những phút giây lúng túng, ngượng ngùng dễ thương. Dù vẫn có những lời bàn tán xôn xao về chuyện của hai người, nhưng trước sự thay đổi tích cực và tự tin của Amane, cách nhìn của mọi người về cậu đã dần thay đổi. Chỉ có duy nhất Mahiru là chẳng hề bận tâm đến những lời xì xào sau lưng ấy.\r\nMùa hè đến, họ cùng nhau đi bơi, về thăm quê nhà của Amane, những kỉ niệm ngọt ngào bên nhau cứ ngày một đong đầy…\r\nChuyện tình ngọt ngào với cô gái nhà bên tuy lạnh lùng nhưng thật đáng yêu rất được ủng hộ trên trang Shousetsuka ni Narou, đã chính thức bước sang một chương mới!'),
(82, 1, 'THIÊN SỨ NHÀ BÊN - TẬP 5.5', '95000.0', 'https://product.hstatic.net/200000343865/product/5.5_cda68d58d46f47bbaada0634900173ad_large.jpg', 2147483647, '978-604-2-28313-7', 308, 'Saekisan', 'Fujimiya Amane - học sinh cấp ba sống tự lập với lối sinh hoạt cẩu thả, và Shiina Mahiru – hoa khôi của trường với biệt danh “thiên sứ”, dù học cùng trường, đồng thời là hàng xóm cạnh nhà nhau, nhưng giữa họ lại chẳng hề có sự kết nối nào. Cho đến một ngày, cuộc gặp gỡ tình cờ của số phận đã thay đổi cuộc sống của họ mãi mãi. Để ngày hôm nay, Mahiru và Amane được ăn cơm chung một nhà.\r\nĐây là tập truyện ngắn khắc họa những khoảnh khắc ngọt ngào trong chuyện tình của chàng trai nhà bên với nàng thiên sứ tuy lạnh lùng nhưng thật đáng yêu, về quá khứ và hiện tại của hai con người đã âm thầm thu hút lẫn nhau ấy.\r\nĐó là một chuyện tình êm đềm và chậm rãi…'),
(83, 1, 'DƯỢC SƯ TỰ SỰ (LIGHT-NOVEL) - TẬP 3', '125000.0', 'https://product.hstatic.net/200000343865/product/3_dfbee7c52edf48aa9aca63a7b742835f_large.jpg', 2147483647, '978-604-2-32018-4', 504, 'Natsu Hyuuga', 'Vì Ngọc Diệp phi có thai, nên Miêu Miêu đã trở lại hậu cung. Nàng lại là sủng phi của Hoàng đế, nên chuyện đó được giữ bí mật cực kì nghiêm ngặt. Tuy nhiên, đàn bà thăm dò lòng dạ nhau vốn là chuyện cơm bữa, không chỉ ở trong hậu cung mà cả từ bên ngoài, những động thái đáng ngờ cứ thoắt ẩn thoắt hiện. \r\nỞ ngoài hậu cung, nhóm Nhâm Thị đang đau đầu trước yêu cầu của đặc sứ nước láng giềng. Các sứ thần đưa ra một bài toán khó đến mức vô lí, đòi gặp mặt nàng kĩ nữ của mấy chục năm trước. Người ta tìm đến xin ý kiến Miêu Miêu, vốn là người thông thạo chuyện của phố hoa. Đó là một nhân vật không ai ngờ tới. Miêu Miêu phải chuẩn bị một mĩ nhân tuyệt sắc khác để thay thế cho nàng kĩ nữ kia. \r\nChưa hết, Miêu Miêu còn phải đồng hành cùng Nhâm Thị đến sơn trang nghỉ mát. Chuyện gì đang chờ đợi họ ở đó…!?'),
(84, 1, 'DƯỢC SƯ TỰ SỰ (MANGA) - TẬP 10', '47000.0', 'https://product.hstatic.net/200000343865/product/10_0f2f7aad29e84b25905b30a6ac06bbfe_large.jpg', 2147483647, '978-604-2-32017-7', 180, 'Natsu Hyuuga', 'Trong tiệc thiết đãi hai nữ đặc sứ đến từ dị quốc, Miêu Miêu đã thực hiện một chiến lược bí mật, làm xuất hiện tiên nữ cung trăng xinh đẹp tại vườn đào vào đêm ngày mười sáu.\r\nSau khi các sứ thần về nước, Miêu Miêu bắt đầu tò mò về hoàn cảnh dầu thơm được đoàn thương buôn mang vào hậu cung...\r\nTrong tập 10 này, Miêu Miêu không chỉ suy luận về bối cảnh của những vụ án từ trước tới nay mà còn phá giải nhiều bí ẩn mới!!'),
(85, 1, 'ARYA BÀN BÊN THỈNH THOẢNG LẠI TRÊU GHẸO TÔI BẰNG TIẾNG NGA - TẬP', '135000.0', 'https://product.hstatic.net/200000343865/product/3---lmt_4b19bd31200d4f099e5c17aac567521b_large.jpg', 2147483647, '978-604-2-28315-1', 440, 'Sunsunsun', '“И наменятоже обрати внимание”\r\nNổi lên sau chiến thắng trong cuộc thi hùng biện, đôi bạn đồng hành Arya và Masachika nhận được vô số lời khen ngợi từ các bạn cùng lớp. Họ đồng tâm quyết chí hướng đến kì bầu cử đang ở phía trước! Cùng lúc đó, Masachika phải nỗ lực học hành để chuẩn bị cho kì thi cuối kì, nhưng duyên nợ không dễ xóa nhòa với gia tộc Suou đã dẫn đến những bước ngoặt không thể ngờ tới...\r\n“Tôi được Yuki nhờ đến chăm bệnh cho cậu.”\r\n“...” [Nói dối đó] (Há!)\r\nKhi Masachika bị ốm, vì lo lắng không yên, Arya đã tới nhà Masachika thăm bệnh!? Sự chăm sóc tận tâm nhưng vụng về của nàng công chúa kiêu ngạo không khỏi khiến cậu phải bật cười.\r\nĐây là Tập 3 của bộ truyện thanh xuân lãng mạn và hài hước về cô nàng nữ sinh trung học gốc Nga xinh đẹp thích che giấu sự ngọt ngào của mình sau những lời trêu ghẹo!'),
(86, 1, 'ARYA BÀN BÊN THỈNH THOẢNG LẠI TRÊU GHẸO TÔI BẰNG TIẾNG NGA - TẬP', '95000.0', 'https://product.hstatic.net/200000343865/product/1_52b3fda7268f4503bd7000f7c814a175_large.jpg', 2147483647, '978-604-2-31333-9', 304, 'Sunsunsun', '“И наменятоже обрати внимание”\r\n“Hở, gì thế?”\r\n“Có gì đâu? Tôi nói ‘Cái tên này đúng là đồ ngốc’ ý mà.”\r\n“Cậu thôi cái trò mắng người ta bằng tiếng Nga đi!?”\r\n\r\nArya - cô nàng xinh đẹp tuyệt trần có mái tóc bạch kim ngồi cạnh tôi - đang nở một nụ cười đắc thắng... \r\n\r\nNhưng sự thật thì, câu tiếng Nga cô ấy vừa nói có nghĩa là [Hãy để ý đến tôi đi] cơ!\r\n\r\nTôi - Kuze Masachika - là người có khả năng nghe hiểu tiếng Nga thông thạo như người bản xứ. Nhưng không hề hay biết điều đó, cô nàng Arya hôm nay vẫn tiếp tục thể hiện những cảm xúc rất ngọt ngào bằng tiếng Nga khiến tôi không thể ngừng cười!?\r\n\r\nCâu chuyện tình thanh xuân hài hước của tôi với cô nàng nữ sinh trung học gốc Nga hoàn hảo đã bắt đầu như thế...'),
(87, 1, 'ARYA BÀN BÊN THỈNH THOẢNG LẠI TRÊU GHẸO TÔI BẰNG TIẾNG NGA - TẬP', '95000.0', 'https://product.hstatic.net/200000343865/product/3_dda045dc59be447fa806d4572ed21b2c_large.jpg', 2147483647, '978-604-2-28316-8', 440, 'Sunsunsun', '“И наменятоже обрати внимание”\r\nNổi lên sau chiến thắng trong cuộc thi hùng biện, đôi bạn đồng hành Arya và Masachika nhận được vô số lời khen ngợi từ các bạn cùng lớp. Họ đồng tâm quyết chí hướng đến kì bầu cử đang ở phía trước! Cùng lúc đó, Masachika phải nỗ lực học hành để chuẩn bị cho kì thi cuối kì, nhưng duyên nợ không dễ xóa nhòa với gia tộc Suou đã dẫn đến những bước ngoặt không thể ngờ tới...\r\n“Tôi được Yuki nhờ đến chăm bệnh cho cậu.”\r\n“...” [Nói dối đó] (Há!)\r\nKhi Masachika bị ốm, vì lo lắng không yên, Arya đã tới nhà Masachika thăm bệnh!? Sự chăm sóc tận tâm nhưng vụng về của nàng công chúa kiêu ngạo không khỏi khiến cậu phải bật cười.\r\nĐây là Tập 3 của bộ truyện thanh xuân lãng mạn và hài hước về cô nàng nữ sinh trung học gốc Nga xinh đẹp thích che giấu sự ngọt ngào của mình sau những lời trêu ghẹo!'),
(88, 1, 'ẨM THỰC CHINH PHỤC THẾ GIỚI - HẠT GẠO , HẠT VÀNG', '55000.0', 'https://product.hstatic.net/200000343865/product/hat-gao-hat-vang_bia_35a68661c20642979aecc4a0825f6a42_large.jpg', 2147483647, '978-604-2-28311-3', 112, 'Nguyên Ánh', 'Từ thuở xa xưa, khi những hạt lúa đầu tiên rơi vào tay con người, lịch sử nhân loại đã vĩnh viễn bước sang một chương mới. Mà ở đó, cuộc sống du canh du cư chỉ còn là quá khứ, loài người đã chọn sống quần cư lâu dài bên những dòng sông đất đai màu mỡ, thuận lợi tưới tiêu, lấy nông nghiệp làm kế sinh nhai. Từ cuộc sống ấm no với hạt gạo dẻo thơm, con người đã xây dựng nên những nền văn minh rực rỡ. Lúa gạo đem lại sự sống, lúa gạo gắn bó với đời sống tinh thần của loài người, và sự kết nối ấy sẽ còn mãi cho đến muôn đời sau…\r\nCuốn sách này kể với bạn về hành trình chinh phục thế giới đầy li kì và hấp dẫn của những hạt gạo tưởng chừng như bé nhỏ, mộc mạc và đơn sơ ấy. \r\n“Ẩm thực về gạo khắp năm châu là một bức tranh muôn vẻ với vô số hình thức chế biến, những món tráng miệng ngọt ngào, cơm trắng đơn giản hay món thập cẩm sắc màu. Dẫu cho bạn thích món khô hay nước, dạng sợi, dạng bánh hoặc xôi chè… gạo đều có thể ‘làm vừa lòng’ bạn.”'),
(89, 1, 'THẾ GIỚI THẤT LẠC ( NHỮNG CUỘC PHIÊU LƯU CỦA GIÁO SƯ CHALLENGER ', '145000.0', 'https://product.hstatic.net/200000343865/product/the-gioi-that-lac_048c8904f6b64e219f9cd3da00b456b7_large.jpg', 2147483647, '978-604-2-28301-4', 308, 'Arthur Conan Doyle', '“Những nỗi kinh hoàng sống động và dữ dội nào đang sẵn sàng nhảy bổ vào chúng tôi từ hang ổ giữa núi đá hay rừng rậm?”\r\nCác sinh vật cổ đại từng một thời làm chủ Trái Đất liệu thật sự đã tuyệt chủng? Cuốn sổ phác hoạ mô tả loài sinh vật lạ được phát hiện trong số đồ đạc để lại của một người Mĩ đã chết ở lưu vực sông Amazon. Người đàn ông duy nhất từng đặt chân tới vùng đất mà nhân loại chưa biết đến rất có thể đã chạm trán với những sinh vật thời tiền sử.\r\nGiáo sư Challenger, cái tên nổi tiếng (và tai tiếng) trong giới học thuật Anh Quốc, cùng các cộng sự dấn thân vào chuyến thám hiểm vùng cao nguyên Amazon xa xôi để tìm kiếm “thế giới thất lạc”. Họ buộc phải học cách sinh tồn tại một nơi hẻo lánh và vô vàn nguy hiểm chực chờ, nơi cái chết và sự sống của con người đã trở thành thông lệ, kẻ vốn đi săn trở thành kẻ bị săn đuổi.\r\nTHẾ GIỚI THẤT LẠC là kiệt tác vượt thời gian của nhà văn Arthur Conan Doyle – bậc thầy về thể loại khoa học viễn tưởng và bí ẩn.\r\n---\r\nARTHUR CONAN DOYLE (1859 - 1930) được hậu thế biết đến rộng rãi với tư cách “cha đẻ” của nhân vật Sherlock Holmes, song di sản của ông không chỉ có vậy. Các tác phẩm của Doyle trải dài trên nhiều thể loại và đều được đánh giá cao. Ông thể hiện mình là một nhà văn có tài trong thể loại truyện ngắn kinh dị, và đã viết một loạt tiểu thuyết lịch sử đáng chú ý, cũng như xuất bản các tác phẩm khoa học viễn tưởng nổi tiếng xoay quanh nhân vật Giáo sư Challenger.\r\nGiáo sư Challenger, cùng với vị thám tử lừng danh, là một trong số ít các nhân vật chính của Doyle được xuất hiện thường xuyên. Và cũng giống như những câu chuyện của Holmes đã “cách mạng hoá” thể loại truyện trinh thám, loạt truyện về Giáo sư Challenger đóng góp đáng kể vào sự phát triển của thể loại khoa học viễn tưởng cùng với các tác phẩm của Jules Verne và H. G. Wells.'),
(90, 1, 'HOLMES Ở KYOTO - TẬP 9', '85000.0', 'https://product.hstatic.net/200000343865/product/9_324435843e07490f8922a4436a970e7b_large.jpg', 2147483647, '978-604-2-32014-6', 366, 'Mai Mochizuki', 'Sang tháng Một, Aoi đã bắt đầu quen với môi trường đại học. Những ngày này, cô chẳng được gặp Kiyotaka, người đang học việc tại “xưởng rượu Kotani”, một xưởng nấu rượu có truyền thống lâu đời ở khu Fushimi ngoại ô thành phố Kyoto. Thời gian gần đây, Aoi hay đến hỗ trợ câu lạc bộ cắm hoa mà cô bạn thân Kaori đang sinh hoạt.\r\nMột ngày nọ, chủ tịch câu lạc bộ, một sinh viên năm ba tên là Ikumi, bất ngờ tuyên bố sẽ nghỉ câu lạc bộ. Trong khi đó, xưởng rượu Kotani được một phen náo động khi bình rượu gia bảo của họ biến mất. Đằng sau mỗi vụ việc đều chứa đựng một nỗi khổ tâm riêng. \r\nNgoài ra, hãy đón xem Kiyotaka và Akihito cùng nhau trổ tài ở chương 3 “Màn diễn trả thù” với bối cảnh là Công viên giải trí Hirakata nhé!'),
(92, 1, 'CHITOSE TRONG CHAI RAMUNE - TẬP 3', '115000.0', 'https://product.hstatic.net/200000343865/product/3--obi_08a062a20b3d451490c2ff18e3a8ddcc_large.jpg', 2147483647, '978-604-2-28314-4', 520, 'Hiromu', '“Vẫn có hiện thực giống như truyện cổ tích mà. Thực ra còn ở ngay gần đấy.”\r\nTừ sau lần chạm mặt trong buổi thảo luận định hướng, tôi và chị Asuka bắt đầu gặp gỡ cả ở trường. Những lần cùng ra ngoài như thể hẹn hò cũng tăng lên, tôi rất vui, nhưng mặt khác lại mang trong lòng thứ cảm xúc có chút gì cay đắng.\r\nDù rằng tôi cũng hiểu, điều đó là vô cùng ích kỉ.\r\n… Chị Asuka sẽ đến Tokyo để theo đuổi giấc mơ của mình.\r\nLiệu tôi có thể tươi cười tiễn người ấy không…?\r\nMột ngày mùa hè xa xôi. Mong rằng ta sẽ được gặp lại nhau.\r\nBộ truyện tình cảm hài về thế giới của các riajuu, mang theo làn gió của thời đại mới, nay đã bước sang Tập 3!!'),
(93, 1, 'THỊ TRẤN MÈO - TẬP 7', '68000.0', 'https://product.hstatic.net/200000343865/product/7_f7e79d52b5d5431380524dbc7669fe3a_large.jpg', 2147483647, '978-604-2-31312-4 ', 176, 'Nekomaki (ms-work)', 'Ông Daikichi lần giở từng trang cuốn album cũ ngủ quên bấy lâu trong hộc tủ. Trong cuốn album đong đầy bao kí ức đầy hoài niệm về chiếc “xế cưng” Subaru 360, thầy “Takayan” đáng kính ở trường cấp một và những bức ảnh của Tsuyoshi khi còn nhỏ.\r\nVà rồi, ông Daikichi tìm thấy cả tấm hình ông cùng vợ mình là bà Yoshie với Tama chụp ngay trước khi bà mất.\r\nQua từng bức ảnh, vô vàn kỉ niệm và kí ức về những người thân yêu cứ lần lượt ùa về. THỊ TRẤN MÈO xin tiếp tục gửi tới bạn đọc những hình ảnh về cuộc sống thường ngày thương mến điểm tô sắc màu của bốn mùa xuân, hạ, thu, đông.\r\nThị trấn mèo êm đềm nằm bên bờ biển, là ngôi nhà chung của các ông bà già cả và những chú mèo. Trong đó có ông lão Daikichi và chú mèo Tama. Người và mèo ngày ngày quấn quýt, bầu bạn bên nhau, trải qua bốn mùa xuân - hạ - thu - đông, tới khi cùng bạc mái đầu.'),
(94, 1, 'THỊ TRẤN MÈO - TẬP 6', '68000.0', 'https://product.hstatic.net/200000343865/product/6_0ca4c2d5dd544cb0a54b6487ce822714_large.jpg', 2147483647, '978-604-2-31311-7', 176, 'Nekomaki (ms-work)', 'Ở một làng chài nằm rìa Tokyo, luôn có hàng dài những chú mèo chiếm lĩnh mọi ngóc ngách của bến cảng, xếp hàng chờ ăn những con cá tươi ngon, béo ngậy vừa đánh bắt ngoài biển khơi về. Dần dần, chả biết chúng từ đâu cứ đến nơi đây, tạo thành khung cảnh có một không hai: một thị trấn đầy ắp những chú mèo trên mọi nẻo đường.\r\n\r\nThị trấn mèo êm đềm nằm bên bờ biển, là ngôi nhà chung của các ông bà già cả và những chú mèo. Trong đó có ông lão Daikichi và chú mèo Tama vừa tròn 10 tuổi.\r\n\r\nNgười và mèo ngày ngày quấn quýt, bầu bạn bên nhau, trải qua bốn mùa xuân - hạ - thu - đông, tới khi cùng bạc mái đầu.'),
(95, 1, 'THỊ TRẤN MÈO - TẬP 5', '68000.0', 'https://product.hstatic.net/200000343865/product/5_26b15368fe5141189dfe207da608724c_large.jpg', 2147483647, '978-604-2-31310-0', 176, 'Nekomaki (ms-work)', 'Ở một làng chài nằm rìa Tokyo, luôn có hàng dài những chú mèo chiếm lĩnh mọi ngóc ngách của bến cảng, xếp hàng chờ ăn những con cá tươi ngon, béo ngậy vừa đánh bắt ngoài biển khơi về. Dần dần, chả biết chúng từ đâu cứ đến nơi đây, tạo thành khung cảnh có một không hai: một thị trấn đầy ắp những chú mèo trên mọi nẻo đường.\r\n\r\nThị trấn mèo êm đềm nằm bên bờ biển, là ngôi nhà chung của các ông bà già cả và những chú mèo. Trong đó có ông lão Daikichi và chú mèo Tama vừa tròn 10 tuổi.\r\n\r\nNgười và mèo ngày ngày quấn quýt, bầu bạn bên nhau, trải qua bốn mùa xuân - hạ - thu - đông, tới khi cùng bạc mái đầu.'),
(96, 1, 'THỊ TRẤN MÈO - TẬP 4', '68000.0', 'https://product.hstatic.net/200000343865/product/4_44d2aea182cf4d65906eff69688b5ea2_large.jpg', 2147483647, '978-604-2-31309-4', 176, 'Nekomaki (ms-work)', 'Ở một làng chài nằm rìa Tokyo, luôn có hàng dài những chú mèo chiếm lĩnh mọi ngóc ngách của bến cảng, xếp hàng chờ ăn những con cá tươi ngon, béo ngậy vừa đánh bắt ngoài biển khơi về. Dần dần, chả biết chúng từ đâu cứ đến nơi đây, tạo thành khung cảnh có một không hai: một thị trấn đầy ắp những chú mèo trên mọi nẻo đường.\r\n\r\nThị trấn mèo êm đềm nằm bên bờ biển, là ngôi nhà chung của các ông bà già cả và những chú mèo. Trong đó có ông lão Daikichi và chú mèo Tama vừa tròn 10 tuổi.\r\n\r\nNgười và mèo ngày ngày quấn quýt, bầu bạn bên nhau, trải qua bốn mùa xuân - hạ - thu - đông, tới khi cùng bạc mái đầu.'),
(97, 1, 'THỊ TRẤN MÈO - TẬP 3', '68000.0', 'https://product.hstatic.net/200000343865/product/3_a4ac8c8c40bc452ba70309c178f4d5cd_large.jpg', 2147483647, '978-604-2-31308-7', 176, 'Nekomaki (ms-work)', 'Ở một làng chài nằm rìa Tokyo, luôn có hàng dài những chú mèo chiếm lĩnh mọi ngóc ngách của bến cảng, xếp hàng chờ ăn những con cá tươi ngon, béo ngậy vừa đánh bắt ngoài biển khơi về. Dần dần, chả biết chúng từ đâu cứ đến nơi đây, tạo thành khung cảnh có một không hai: một thị trấn đầy ắp những chú mèo trên mọi nẻo đường.\r\n\r\nThị trấn mèo êm đềm nằm bên bờ biển, là ngôi nhà chung của các ông bà già cả và những chú mèo. Trong đó có ông lão Daikichi và chú mèo Tama vừa tròn 10 tuổi.\r\n\r\nNgười và mèo ngày ngày quấn quýt, bầu bạn bên nhau, trải qua bốn mùa xuân - hạ - thu - đông, tới khi cùng bạc mái đầu.'),
(98, 1, 'THỊ TRẤN MÈO - TẬP 8', '68000.0', 'https://product.hstatic.net/200000343865/product/8_b4347092c2654712b66e863621b24c1c_large.jpg', 2147483647, '978-604-2-28321-2', 176, 'Nekomaki (ms-work)', 'Ông Daikichi bồi hồi nhớ lại hộp cơm cốt lết chiên xù mẹ chuẩn bị cho ông vào ngày ứng thí, hộp cơm “bóng tối” ông ăn cùng vợ trong căn nhà mất điện tối om và hộp cơm bằng nhôm thời chiến tranh một cậu bạn mang về quê sơ tán.\r\n\r\nNhững mẩu truyện xoay quanh hộp cơm thay phiên xuất hiện trong tập này có lẽ sẽ khiến chúng ta vừa đọc vừa đói bụng.\r\n\r\nMời các bạn tiếp tục theo dõi cuộc sống trên đảo của các ông lão, bà lão cùng những chú mèo được điểm tô sắc màu của bốn mùa xuân, hạ, thu, đông.'),
(99, 1, 'THỊ TRẤN MÈO - TẬP 2', '68800.0', 'https://product.hstatic.net/200000343865/product/2_8c35086bf43143c19cc54165c9e2a535_large.jpg', 2147483647, '978-604-2-31307-0', 176, 'Nekomaki (ms-work)', 'Ở một làng chài nằm rìa Tokyo, luôn có hàng dài những chú mèo chiếm lĩnh mọi ngóc ngách của bến cảng, xếp hàng chờ ăn những con cá tươi ngon, béo ngậy vừa đánh bắt ngoài biển khơi về. Dần dần, chả biết chúng từ đâu cứ đến nơi đây, tạo thành khung cảnh có một không hai: một thị trấn đầy ắp những chú mèo trên mọi nẻo đường.\r\n\r\nThị trấn mèo êm đềm nằm bên bờ biển, là ngôi nhà chung của các ông bà già cả và những chú mèo. Trong đó có ông lão Daikichi và chú mèo Tama vừa tròn 10 tuổi.\r\n\r\nNgười và mèo ngày ngày quấn quýt, bầu bạn bên nhau, trải qua bốn mùa xuân - hạ - thu - đông, tới khi cùng bạc mái đầu.'),
(101, 1, 'THIÊN SỨ NHÀ BÊN - TẬP 7', '85500.0', 'https://product.hstatic.net/200000343865/product/7_cf288c862633493186597c48736af766_large.jpg', 2147483647, '978-604-2-32900-2', 336, 'Saekisan', 'Kết thúc kì nghỉ hè, khắp trường bắt đầu nhộn nhịp chuẩn bị cho lễ hội văn hóa. Các bạn cùng lớp dường như đã quen với sự thân mật của cặp đôi Amane và Mahiru, mỗi ngày họ đều dõi theo cả hai bằng ánh mắt thích thú.\r\nTrong lễ hội văn hóa, lớp Amane quyết định mở quán giải khát quản gia - hầu gái. Thấy các bạn cùng lớp đều phấn khích khi nhìn “thiên sứ” trong bộ trang phục hầu gái, Amane không khỏi khó chịu khi nghĩ đến việc Mahiru sẽ bị nhiều ánh mắt dòm ngó. Mặt khác, Mahiru cũng cảm thấy lo lắng khi Amane dần cởi mở với mọi người xung quanh và ngày càng được các cô gái chú ý tới...\r\nĐây là câu chuyện tình ngọt ngào với cô gái nhà bên tuy lạnh lùng nhưng thật đáng yêu đã được ủng hộ nhiệt tình trên trang Shousetsuka ni Narou.'),
(102, 1, 'DẾ MÈN PHIÊU LƯU KÝ', '45000.0', 'https://product.hstatic.net/200000343865/product/de-men-phieu-luu-ky-_13x19_bia_tb2019-1_1b338ee424b540bb8f4a86590e1fe0f9_large.jpg', 2147483647, '978-604-2-31143-4', 192, 'Tô Hoài', '“Biết ước mơ và hành động, Dế mèn của tôi chắc chắn là bạn trung thủy với thế hệ tuổi thơ của bạn.”\r\n\r\nTô Hoài\r\n\r\n“Một con dế đã từ tay ông thả ra chu du thế giới tìm những điều tốt đẹp cho loài người. Và con dế ấy đã mang tên tuổi ông đi cùng trên những chặng đường phiêu lưu đến với cộng đồng những con vật trong văn học thế giới, đến với những xứ sở thiên nhiên và văn hóa của các quốc gia khác. Dế Mèn Tô Hoài đã lại sinh ra Tô Hoài Dế Mèn, một nhà văn trẻ mãi không già trong văn chương...”\r\n\r\n- Nhà phê bình Phạm Xuân Nguyên-\r\n\r\n“Ông rất hiểu tư duy trẻ thơ, kể với chúng theo cách nghĩ của chúng,lí giải sự vật theo lô gích của trẻ. Hơn thế, với biệt tài miêu tả loài vật, Tô Hoài dựng lên một thế giới gần gũi với trẻ thơ. Khi cần, ông biết đem vào chất du ký khiến cho độc giả nhỏ tuổi vừa hồi hộp theo dõi, vừa thích thú khám phá.”\r\n\r\n- TS. Nguyễn Đăng Điệp -');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `user`
--

CREATE TABLE `user` (
  `id_user` int(20) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(20) NOT NULL,
  `phone` varchar(32) DEFAULT NULL,
  `address` varchar(32) DEFAULT NULL,
  `name` varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Đang đổ dữ liệu cho bảng `user`
--

INSERT INTO `user` (`id_user`, `username`, `password`, `phone`, `address`, `name`) VALUES
(31, 'hoanghuy', '061199', '0369859916', 'Tầm Vu', 'Hoàng Huy'),
(32, 'nilou', 'nilou', '0888777666', 'sumeru', 'nilou');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id_admin`);

--
-- Chỉ mục cho bảng `catalog`
--
ALTER TABLE `catalog`
  ADD PRIMARY KEY (`id_catalog`);

--
-- Chỉ mục cho bảng `hoadon`
--
ALTER TABLE `hoadon`
  ADD PRIMARY KEY (`id_order`);

--
-- Chỉ mục cho bảng `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id_product`),
  ADD KEY `product_ibfk_1` (`id_catalog`);

--
-- Chỉ mục cho bảng `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id_user`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `admin`
--
ALTER TABLE `admin`
  MODIFY `id_admin` int(32) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT cho bảng `catalog`
--
ALTER TABLE `catalog`
  MODIFY `id_catalog` int(32) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT cho bảng `hoadon`
--
ALTER TABLE `hoadon`
  MODIFY `id_order` int(32) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT cho bảng `product`
--
ALTER TABLE `product`
  MODIFY `id_product` int(32) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=103;

--
-- AUTO_INCREMENT cho bảng `user`
--
ALTER TABLE `user`
  MODIFY `id_user` int(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `product`
--
ALTER TABLE `product`
  ADD CONSTRAINT `product_ibfk_1` FOREIGN KEY (`id_catalog`) REFERENCES `catalog` (`id_catalog`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
